; Hand-written assembly: the Matrox edition's 16-bit 2D primitives, a MASM object assembled with
; MASM 6.11 (ML). Its code starts at 0x100563dc, 4-aligned after loadres.c's (two bytes of 0xCC
; where a compiled object would start 16-aligned), and its data at 0x100aab34. It is a port of
; VFX 1.15's VFXA (3rdparty/vfx/VFXA.ASM) to 16-bit pixels: VFXA's routines in VFXA's order, with
; ML's PROC C USES ebx esi edi es frames, and VFXA's .DATA layout (unaligned after driver_name, as
; there). The routines that draw address pixels as words and take 16-bit colors; the others are
; VFXA's unchanged, 8-bit ones included (VFX_window_fade16, VFX_color_scan16). It leaves out
; VFX_rectangle_hash, the translated, transformed and scanned shapes, VFX_shape_remap_colors,
; VFX_pane_copy and VFX_pane_scroll, VFX_ellipse_fill, the picture formats, the shape queries and
; VFX_pixel_fade, and adds two lookaside routines. Miles's own 16-bit VFX (WINVFX16.ASM, July 1996
; onward) is a later, STDCALL, pixel_pitch-based derivation and doesn't match. The ATI and S3
; editions carry the object too. Generated by tools/asm2masm.py from the original; annotated by
; name in matrox/vfx16.h. Only the Matrox edition links it, built with ML, so it has no portable C.

	.386
	.model flat, c
	option noscoped
	option casemap:none

	.data

; VFXA's driver table, copied by VFX_register_driver16.
	public VFX_describe_driver16
VFX_describe_driver16_t struct
m_data db 4 dup (0)
VFX_describe_driver16_t ends
VFX_describe_driver16 VFX_describe_driver16_t <>

	public VFX_init_driver16
VFX_init_driver16_t struct
m_data db 4 dup (0)
VFX_init_driver16_t ends
VFX_init_driver16 VFX_init_driver16_t <>

	public VFX_shutdown_driver16
VFX_shutdown_driver16_t struct
m_data db 4 dup (0)
VFX_shutdown_driver16_t ends
VFX_shutdown_driver16 VFX_shutdown_driver16_t <>

	public VFX_area_wipe16
VFX_area_wipe16_t struct
m_data db 4 dup (0)
VFX_area_wipe16_t ends
VFX_area_wipe16 VFX_area_wipe16_t <>

	public VFX_wait_vblank16
VFX_wait_vblank16_t struct
m_data db 4 dup (0)
VFX_wait_vblank16_t ends
VFX_wait_vblank16 VFX_wait_vblank16_t <>

	public VFX_wait_vblank_leading16
VFX_wait_vblank_leading16_t struct
m_data db 4 dup (0)
VFX_wait_vblank_leading16_t ends
VFX_wait_vblank_leading16 VFX_wait_vblank_leading16_t <>

	public VFX_window_refresh16
VFX_window_refresh16_t struct
m_data db 4 dup (0)
VFX_window_refresh16_t ends
VFX_window_refresh16 VFX_window_refresh16_t <>

	public VFX_window_read16
VFX_window_read16_t struct
m_data db 4 dup (0)
VFX_window_read16_t ends
VFX_window_read16 VFX_window_read16_t <>

	public VFX_DAC_read16
VFX_DAC_read16_t struct
m_data db 4 dup (0)
VFX_DAC_read16_t ends
VFX_DAC_read16 VFX_DAC_read16_t <>

	public VFX_DAC_write16
VFX_DAC_write16_t struct
m_data db 4 dup (0)
VFX_DAC_write16_t ends
VFX_DAC_write16 VFX_DAC_write16_t <>

	public VFX_bank_reset16
VFX_bank_reset16_t struct
m_data db 4 dup (0)
VFX_bank_reset16_t ends
VFX_bank_reset16 VFX_bank_reset16_t <>

	public VFX_pane_refresh16
VFX_pane_refresh16_t struct
m_data db 4 dup (0)
VFX_pane_refresh16_t ends
VFX_pane_refresh16 VFX_pane_refresh16_t <>

	public VFX_line_address16
VFX_line_address16_t struct
m_data db 4 dup (0)
VFX_line_address16_t ends
VFX_line_address16 VFX_line_address16_t <>

; VFXA's driver name buffer, filled by VFX_driver_name16.
	public driver_name16
driver_name16_t struct
m_data db 4dh, 43h, 47h, 41h, 2eh, 44h, 4ch, 4ch, 5 dup (0)
driver_name16_t ends
driver_name16 driver_name16_t <>

; VFXA's VFX_shape_scan variables (VFX_shape_scan isn't in the port).
	public SHP_building16
SHP_building16_t struct
m_data db 4 dup (0)
SHP_building16_t ends
SHP_building16 SHP_building16_t <>

	public SHP_skipCount16
SHP_skipCount16_t struct
m_data db 4 dup (0)
SHP_skipCount16_t ends
SHP_skipCount16 SHP_skipCount16_t <>

	public SHP_LinePtr16
SHP_LinePtr16_t struct
m_data db 4 dup (0)
SHP_LinePtr16_t ends
SHP_LinePtr16 SHP_LinePtr16_t <>

	public SHP_ScanPtr16
SHP_ScanPtr16_t struct
m_data db 4 dup (0)
SHP_ScanPtr16_t ends
SHP_ScanPtr16 SHP_ScanPtr16_t <>

	public SHP_ShapePtr16
SHP_ShapePtr16_t struct
m_data db 4 dup (0)
SHP_ShapePtr16_t ends
SHP_ShapePtr16 SHP_ShapePtr16_t <>

	public SHP_FlushPtr16
SHP_FlushPtr16_t struct
m_data db 4 dup (0)
SHP_FlushPtr16_t ends
SHP_FlushPtr16 SHP_FlushPtr16_t <>

	public SHP_CP_L16
SHP_CP_L16_t struct
m_data db 4 dup (0)
SHP_CP_L16_t ends
SHP_CP_L16 SHP_CP_L16_t <>

	public SHP_CP_T16
SHP_CP_T16_t struct
m_data db 4 dup (0)
SHP_CP_T16_t ends
SHP_CP_T16 SHP_CP_T16_t <>

	public SHP_CP_R16
SHP_CP_R16_t struct
m_data db 4 dup (0)
SHP_CP_R16_t ends
SHP_CP_R16 SHP_CP_R16_t <>

	public SHP_CP_B16
SHP_CP_B16_t struct
m_data db 4 dup (0)
SHP_CP_B16_t ends
SHP_CP_B16 SHP_CP_B16_t <>

	public SHP_minX16
SHP_minX16_t struct
m_data db 4 dup (0)
SHP_minX16_t ends
SHP_minX16 SHP_minX16_t <>

	public SHP_minY16
SHP_minY16_t struct
m_data db 4 dup (0)
SHP_minY16_t ends
SHP_minY16 SHP_minY16_t <>

	public SHP_maxX16
SHP_maxX16_t struct
m_data db 4 dup (0)
SHP_maxX16_t ends
SHP_maxX16 SHP_maxX16_t <>

	public SHP_maxY16
SHP_maxY16_t struct
m_data db 4 dup (0)
SHP_maxY16_t ends
SHP_maxY16 SHP_maxY16_t <>

; VFXA's picture and fade buffers: src_ytable/temp_bufferA.
	public temp_bufferA16
temp_bufferA16_t struct
m_data db 500h dup (0)
temp_bufferA16_t ends
temp_bufferA16 temp_bufferA16_t <>

; Used by VFX_window_fade16 (VFXA's color_buffer).
	public color_buffer16
color_buffer16_t struct
m_data db 300h dup (0)
color_buffer16_t ends
color_buffer16 color_buffer16_t <>

	public color_list16
color_list16_t struct
m_data db 100h dup (0)
color_list16_t ends
color_list16 color_list16_t <>

	public color_delta16
color_delta16_t struct
m_data db 300h dup (0)
color_delta16_t ends
color_delta16 color_delta16_t <>

; dest_ytable/temp_buffer7.
	public dest_ytable16
dest_ytable16_t struct
m_data db 600h dup (0)
dest_ytable16_t ends
dest_ytable16 dest_ytable16_t <>

; VFXA's color_sb and color_vector, the score board of VFX_color_scan16 and VFX_window_fade16.
	public color_sb16
color_sb16_t struct
m_data db 300h dup (0)
color_sb16_t ends
color_sb16 color_sb16_t <>

	public color_error16
color_error16_t struct
m_data db 300h dup (0)
color_error16_t ends
color_error16 color_error16_t <>

; VFXA's GIF tables (the GIF routines aren't in the port).
	public GIF_cmask16
GIF_cmask16_t struct
m_data db 0, 1, 3, 7, 0fh, 1fh, 3fh, 7fh, 0ffh
GIF_cmask16_t ends
GIF_cmask16 GIF_cmask16_t <>

	public GIF_inctable16
GIF_inctable16_t struct
m_data db 8, 8, 4, 2, 0
GIF_inctable16_t ends
GIF_inctable16 GIF_inctable16_t <>

	public GIF_starttable16
GIF_starttable16_t struct
m_data db 0, 4, 2, 1, 0
GIF_starttable16_t ends
GIF_starttable16 GIF_starttable16_t <>

	public GIF_pane16
GIF_pane16_t struct
m_data db 4 dup (0)
GIF_pane16_t ends
GIF_pane16 GIF_pane16_t <>

; The shape lookaside table: a 16-bit pixel for each 8-bit color of a shape.
	public lookaside16
lookaside16_t struct
m_data dw 100h dup (0)
lookaside16_t ends
lookaside16 lookaside16_t <>

; VFXA's VFX_shape_transform vertices (VFX_shape_transform isn't in the port).
	public vert0_16
vert0_16_t struct
m_data db 14h dup (0)
vert0_16_t ends
vert0_16 vert0_16_t <>

	public vert1_16
vert1_16_t struct
m_data db 14h dup (0)
vert1_16_t ends
vert1_16 vert1_16_t <>

	public vert2_16
vert2_16_t struct
m_data db 14h dup (0)
vert2_16_t ends
vert2_16 vert2_16_t <>

	public vert3_16
vert3_16_t struct
m_data db 14h dup (0)
vert3_16_t ends
vert3_16 vert3_16_t <>

	public src_step16
src_step16_t struct
m_data db 10h dup (0)
src_step16_t ends
src_step16 src_step16_t <>

	.code

; VFXA's VFX_driver_name, unchanged.
VFX_driver_name16 proc uses ebx esi edi, p_vfxScanDll:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_vfxScanDll
	call dword ptr [esi]
	mov edi, offset driver_name16
jmp_100563f0:
	mov bl, byte ptr [eax]
	mov byte ptr [edi], bl
	inc edi
	inc eax
	or bl, bl
	jne jmp_100563f0
	mov eax, offset driver_name16
	pop es
	ret
VFX_driver_name16 endp

; VFXA's VFX_register_driver, unchanged.
VFX_register_driver16 proc uses ebx esi edi, p_dllBase:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_dllBase
	mov edi, offset VFX_describe_driver16
	mov ecx, 0dh
	rep movsd
	pop es
	ret
VFX_register_driver16 endp

; VFXA's VFX_pixel_write, for 16-bit pixels: writes the color's low word and returns the old pixel.
VFX_pixel_write16 proc uses ebx esi edi, p_pane:dword, p_x:dword, p_y:dword, p_color:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x18, eax
	jle jmp_100564a8
	shl eax, 1
	mov dword ptr l_unk0x1c, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_100564a8
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x20, eax
	cmp eax, 0
	jg jmp_1005645c
	mov eax, 0
jmp_1005645c:
	mov dword ptr l_unk0x04, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x24, eax
	cmp eax, 0
	jg jmp_1005646f
	mov eax, 0
jmp_1005646f:
	mov dword ptr l_unk0x08, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x18
	dec edx
	cmp eax, edx
	jl jmp_1005647f
	mov eax, edx
jmp_1005647f:
	mov dword ptr l_unk0x0c, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_1005648e
	mov eax, edx
jmp_1005648e:
	mov dword ptr l_unk0x10, eax
	mov eax, dword ptr l_unk0x0c
	cmp eax, dword ptr l_unk0x04
	jl jmp_100564b3
	mov eax, dword ptr l_unk0x10
	cmp eax, dword ptr l_unk0x08
	jl jmp_100564b3
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x14, eax
	jmp jmp_100564be
jmp_100564a8:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_100564b3:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_100564be:
	mov ecx, dword ptr p_x
	mov ebx, dword ptr p_y
	add ecx, dword ptr l_unk0x20
	add ebx, dword ptr l_unk0x24
	cmp ecx, dword ptr l_unk0x04
	jl jmp_100564fe
	cmp ecx, dword ptr l_unk0x0c
	jg jmp_100564fe
	cmp ebx, dword ptr l_unk0x08
	jl jmp_100564fe
	cmp ebx, dword ptr l_unk0x10
	jg jmp_100564fe
	mov eax, ebx
	imul dword ptr l_unk0x18
	add eax, ecx
	add eax, ecx
	add eax, dword ptr l_unk0x14
	mov ebx, eax
	xor eax, eax
	mov ax, word ptr [ebx]
	mov dx, word ptr p_color
	mov word ptr [ebx], dx
	pop es
	ret
jmp_100564fe:
	mov eax, 0fffffffdh
	pop es
	ret
VFX_pixel_write16 endp

; VFXA's VFX_pixel_read, for 16-bit pixels.
VFX_pixel_read16 proc uses ebx esi edi, p_pane:dword, p_x:dword, p_y:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x18, eax
	jle jmp_1005658d
	shl eax, 1
	mov dword ptr l_unk0x1c, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_1005658d
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x20, eax
	cmp eax, 0
	jg jmp_10056541
	mov eax, 0
jmp_10056541:
	mov dword ptr l_unk0x04, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x24, eax
	cmp eax, 0
	jg jmp_10056554
	mov eax, 0
jmp_10056554:
	mov dword ptr l_unk0x08, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x18
	dec edx
	cmp eax, edx
	jl jmp_10056564
	mov eax, edx
jmp_10056564:
	mov dword ptr l_unk0x0c, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_10056573
	mov eax, edx
jmp_10056573:
	mov dword ptr l_unk0x10, eax
	mov eax, dword ptr l_unk0x0c
	cmp eax, dword ptr l_unk0x04
	jl jmp_10056598
	mov eax, dword ptr l_unk0x10
	cmp eax, dword ptr l_unk0x08
	jl jmp_10056598
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x14, eax
	jmp jmp_100565a3
jmp_1005658d:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_10056598:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_100565a3:
	mov ecx, dword ptr p_x
	mov ebx, dword ptr p_y
	add ecx, dword ptr l_unk0x20
	add ebx, dword ptr l_unk0x24
	cmp ecx, dword ptr l_unk0x04
	jl jmp_100565dc
	cmp ecx, dword ptr l_unk0x0c
	jg jmp_100565dc
	cmp ebx, dword ptr l_unk0x08
	jl jmp_100565dc
	cmp ebx, dword ptr l_unk0x10
	jg jmp_100565dc
	mov eax, ebx
	imul dword ptr l_unk0x18
	add eax, ecx
	add eax, ecx
	add eax, dword ptr l_unk0x14
	mov ebx, eax
	xor eax, eax
	mov ax, word ptr [ebx]
	pop es
	ret
jmp_100565dc:
	mov eax, 0fffffffdh
	pop es
	ret
VFX_pixel_read16 endp

; VFXA's VFX_line_draw, for 16-bit pixels.
VFX_line_draw16 proc uses ebx esi edi, p_pane:dword, p_x0:dword, p_y0:dword, p_x1:dword, p_y1:dword, p_mode:dword, p_parm:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword, l_unk0x28:dword, l_unk0x2c:dword, l_unk0x30:dword
	local l_unk0x34:dword, l_unk0x38:dword, l_unk0x3c:dword, l_unk0x40:dword, l_unk0x44:dword, l_unk0x48:dword
	local l_unk0x4c:dword, l_unk0x50:dword, l_unk0x54:dword, l_unk0x58:dword, l_unk0x5c:dword
	push es
	cld
	push ds
	pop es
	cmp dword ptr p_mode, 0
	je jmp_10056605
	mov eax, 0fffffffdh
	pop es
	ret
jmp_10056605:
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x50, eax
	jle jmp_1005667c
	shl eax, 1
	mov dword ptr l_unk0x54, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_1005667c
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x58, eax
	cmp eax, 0
	jg jmp_10056630
	mov eax, 0
jmp_10056630:
	mov dword ptr l_unk0x3c, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x5c, eax
	cmp eax, 0
	jg jmp_10056643
	mov eax, 0
jmp_10056643:
	mov dword ptr l_unk0x40, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x50
	dec edx
	cmp eax, edx
	jl jmp_10056653
	mov eax, edx
jmp_10056653:
	mov dword ptr l_unk0x44, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_10056662
	mov eax, edx
jmp_10056662:
	mov dword ptr l_unk0x48, eax
	mov eax, dword ptr l_unk0x44
	cmp eax, dword ptr l_unk0x3c
	jl jmp_10056687
	mov eax, dword ptr l_unk0x48
	cmp eax, dword ptr l_unk0x40
	jl jmp_10056687
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x4c, eax
	jmp jmp_10056692
jmp_1005667c:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_10056687:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_10056692:
	mov eax, dword ptr l_unk0x58
	add dword ptr p_x0, eax
	add dword ptr p_x1, eax
	mov eax, dword ptr l_unk0x5c
	add dword ptr p_y0, eax
	add dword ptr p_y1, eax
	mov eax, dword ptr p_x1
	sub eax, dword ptr p_x0
	mov dword ptr l_unk0x04, eax
	cdq
	mov dword ptr l_unk0x0c, edx
	xor eax, edx
	sub eax, edx
	mov dword ptr l_unk0x08, eax
	mov eax, dword ptr p_y1
	sub eax, dword ptr p_y0
	mov dword ptr l_unk0x10, eax
	cdq
	mov dword ptr l_unk0x18, edx
	xor eax, edx
	sub eax, edx
	mov dword ptr l_unk0x14, eax
	mov eax, dword ptr p_x0
	mov dword ptr l_unk0x24, eax
	mov eax, dword ptr p_x1
	mov dword ptr l_unk0x2c, eax
	mov eax, dword ptr p_y0
	mov dword ptr l_unk0x28, eax
	mov eax, dword ptr p_y1
	mov dword ptr l_unk0x30, eax
	cmp dword ptr l_unk0x04, 0
	je jmp_10056e76
	cmp dword ptr l_unk0x10, 0
	je jmp_10056f01
	mov eax, dword ptr l_unk0x0c
	xor eax, dword ptr l_unk0x18
	mov dword ptr l_unk0x1c, eax
	mov edx, dword ptr l_unk0x08
	mov ebx, dword ptr l_unk0x14
	mov eax, 0ffffffffh
	cmp edx, ebx
	je jmp_10056718
	jl jmp_10056714
	xchg edx, ebx
jmp_10056714:
	xor eax, eax
	div ebx
jmp_10056718:
	mov dword ptr l_unk0x20, eax
	mov dword ptr l_unk0x34, 0
jmp_10056722:
	xor edx, edx
	mov eax, dword ptr l_unk0x24
	sub eax, dword ptr l_unk0x3c
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x44
	sub eax, dword ptr l_unk0x24
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr l_unk0x40
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x48
	sub eax, dword ptr l_unk0x28
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x2c
	sub eax, dword ptr l_unk0x3c
	shl eax, 1
	adc dh, dh
	mov eax, dword ptr l_unk0x44
	sub eax, dword ptr l_unk0x2c
	shl eax, 1
	adc dh, dh
	mov eax, dword ptr l_unk0x30
	sub eax, dword ptr l_unk0x40
	shl eax, 1
	adc dh, dh
	mov eax, dword ptr l_unk0x48
	sub eax, dword ptr l_unk0x30
	shl eax, 1
	adc dh, dh
	or dword ptr l_unk0x34, edx
	or edx, edx
	je jmp_10056ae1
	test dl, dh
	jne jmp_10057062
	mov ebx, dword ptr l_unk0x08
	cmp ebx, dword ptr l_unk0x14
	jl jmp_100567dc
	test dl, 8
	jne jmp_10056825
	test dl, 4
	jne jmp_10056879
	test dl, 2
	jne jmp_100568fd
	test dl, 1
	jne jmp_10056955
	test dh, 8
	jne jmp_10056985
	test dh, 4
	jne jmp_100569e0
	test dh, 2
	jne jmp_10056a5f
	test dh, 1
	jne jmp_10056ab6
	jmp jmp_10056722
jmp_100567dc:
	test dl, 8
	jne jmp_1005684d
	test dl, 4
	jne jmp_100568a5
	test dl, 2
	jne jmp_100568d5
	test dl, 1
	jne jmp_10056929
	test dh, 8
	jne jmp_100569b1
	test dh, 4
	jne jmp_10056a08
	test dh, 2
	jne jmp_10056a33
	test dh, 1
	jne jmp_10056a8e
	jmp jmp_10056722
jmp_10056825:
	mov eax, dword ptr l_unk0x3c
	mov dword ptr l_unk0x24, eax
	sub eax, dword ptr p_x0
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x28, eax
	jmp jmp_10056722
jmp_1005684d:
	mov eax, dword ptr l_unk0x3c
	mov dword ptr l_unk0x24, eax
	sub eax, dword ptr p_x0
	mov edx, eax
	dec edx
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, -1
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x28, eax
	jmp jmp_10056722
jmp_10056879:
	mov eax, dword ptr l_unk0x44
	mov dword ptr l_unk0x24, eax
	sub eax, dword ptr p_x0
	neg eax
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x28, eax
	jmp jmp_10056722
jmp_100568a5:
	mov eax, dword ptr l_unk0x44
	mov dword ptr l_unk0x24, eax
	sub eax, dword ptr p_x0
	neg eax
	mov edx, eax
	dec edx
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, -1
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x28, eax
	jmp jmp_10056722
jmp_100568d5:
	mov eax, dword ptr l_unk0x40
	mov dword ptr l_unk0x28, eax
	sub eax, dword ptr p_y0
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x24, eax
	jmp jmp_10056722
jmp_100568fd:
	mov eax, dword ptr l_unk0x40
	mov dword ptr l_unk0x28, eax
	sub eax, dword ptr p_y0
	mov edx, eax
	dec edx
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, -1
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x24, eax
	jmp jmp_10056722
jmp_10056929:
	mov eax, dword ptr l_unk0x48
	mov dword ptr l_unk0x28, eax
	sub eax, dword ptr p_y0
	neg eax
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x24, eax
	jmp jmp_10056722
jmp_10056955:
	mov eax, dword ptr l_unk0x48
	mov dword ptr l_unk0x28, eax
	sub eax, dword ptr p_y0
	neg eax
	mov edx, eax
	dec edx
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, -1
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x24, eax
	jmp jmp_10056722
jmp_10056985:
	mov eax, dword ptr l_unk0x3c
	mov dword ptr l_unk0x2c, eax
	sub eax, dword ptr p_x0
	neg eax
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x30, eax
	jmp jmp_10056722
jmp_100569b1:
	mov eax, dword ptr l_unk0x3c
	mov dword ptr l_unk0x2c, eax
	sub eax, dword ptr p_x0
	neg eax
	mov edx, eax
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, 0
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x30, eax
	jmp jmp_10056722
jmp_100569e0:
	mov eax, dword ptr l_unk0x44
	mov dword ptr l_unk0x2c, eax
	sub eax, dword ptr p_x0
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x30, eax
	jmp jmp_10056722
jmp_10056a08:
	mov eax, dword ptr l_unk0x44
	mov dword ptr l_unk0x2c, eax
	sub eax, dword ptr p_x0
	mov edx, eax
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, 0
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_y0
	mov dword ptr l_unk0x30, eax
	jmp jmp_10056722
jmp_10056a33:
	mov eax, dword ptr l_unk0x40
	mov dword ptr l_unk0x30, eax
	sub eax, dword ptr p_y0
	neg eax
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x2c, eax
	jmp jmp_10056722
jmp_10056a5f:
	mov eax, dword ptr l_unk0x40
	mov dword ptr l_unk0x30, eax
	sub eax, dword ptr p_y0
	neg eax
	mov edx, eax
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, 0
	mov edx, dword ptr l_unk0x1c
	not edx
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x2c, eax
	jmp jmp_10056722
jmp_10056a8e:
	mov eax, dword ptr l_unk0x48
	mov dword ptr l_unk0x30, eax
	sub eax, dword ptr p_y0
	mul dword ptr l_unk0x20
	add eax, 80000000h
	adc edx, 0
	mov eax, edx
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x2c, eax
	jmp jmp_10056722
jmp_10056ab6:
	mov eax, dword ptr l_unk0x48
	mov dword ptr l_unk0x30, eax
	sub eax, dword ptr p_y0
	mov edx, eax
	mov eax, 80000000h
	div dword ptr l_unk0x20
	cmp edx, 1
	sbb eax, 0
	mov edx, dword ptr l_unk0x1c
	xor eax, edx
	sub eax, edx
	add eax, dword ptr p_x0
	mov dword ptr l_unk0x2c, eax
	jmp jmp_10056722
jmp_10056ae1:
	mov eax, dword ptr l_unk0x28
	imul dword ptr l_unk0x50
	add eax, dword ptr l_unk0x24
	add eax, dword ptr l_unk0x24
	add eax, dword ptr l_unk0x4c
	mov edi, eax
	mov esi, dword ptr l_unk0x50
	xor esi, dword ptr l_unk0x18
	sub esi, dword ptr l_unk0x18
	mov ebx, dword ptr l_unk0x20
	mov eax, dword ptr l_unk0x08
	cmp eax, dword ptr l_unk0x14
	je jmp_10056f89
	jg jmp_10056cb0
	mov eax, dword ptr l_unk0x30
	sub eax, dword ptr l_unk0x28
	cdq
	xor eax, edx
	sub eax, edx
	inc eax
	mov ecx, eax
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr p_y0
	cdq
	xor eax, edx
	sub eax, edx
	mul ebx
	add eax, 80000000h
	mov edx, eax
	cmp dword ptr l_unk0x0c, -1
	je jmp_10056bf5
	cmp dword ptr p_mode, 1
	je jmp_10056b8c
	jg jmp_10056bca
	mov eax, dword ptr p_parm
jmp_10056b4b:
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056b55
	add edi, 2
jmp_10056b55:
	add edi, esi
	dec ecx
	je jmp_10056b87
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056b64
	add edi, 2
jmp_10056b64:
	add edi, esi
	dec ecx
	je jmp_10056b87
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056b73
	add edi, 2
jmp_10056b73:
	add edi, esi
	dec ecx
	je jmp_10056b87
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056b82
	add edi, 2
jmp_10056b82:
	add edi, esi
	dec ecx
	jne jmp_10056b4b
jmp_10056b87:
	jmp jmp_10057053
jmp_10056b8c:
	mov eax, dword ptr p_parm
	push ebp
	mov ebp, ebx
	mov ebx, eax
jmp_10056b94:
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	add edi, esi
	dec ecx
	je jmp_10056bc4
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	add edi, esi
	dec ecx
	je jmp_10056bc4
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	add edi, esi
	dec ecx
	je jmp_10056bc4
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	add edi, esi
	dec ecx
	jne jmp_10056b94
jmp_10056bc4:
	pop ebp
	jmp jmp_10057053
jmp_10056bca:
	mov esi, dword ptr p_pane
	mov edi, dword ptr l_unk0x24
	sub edi, dword ptr [esi+4]
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr [esi+8]
	mov esi, eax
	mov eax, dword ptr l_unk0x18
	add eax, eax
	inc eax
jmp_10056be1:
	pushad
	call dword ptr p_parm
	popad
	add edx, ebx
	jae jmp_10056beb
	inc edi
jmp_10056beb:
	add esi, eax
	dec ecx
	jne jmp_10056be1
	jmp jmp_10057053
jmp_10056bf5:
	neg esi
	cmp dword ptr p_mode, 1
	je jmp_10056c47
	jg jmp_10056c85
	mov eax, dword ptr p_parm
jmp_10056c06:
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056c10
	sub edi, 2
jmp_10056c10:
	sub edi, esi
	dec ecx
	je jmp_10056c42
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056c1f
	sub edi, 2
jmp_10056c1f:
	sub edi, esi
	dec ecx
	je jmp_10056c42
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056c2e
	sub edi, 2
jmp_10056c2e:
	sub edi, esi
	dec ecx
	je jmp_10056c42
	mov word ptr [edi], ax
	add edx, ebx
	jae jmp_10056c3d
	sub edi, 2
jmp_10056c3d:
	sub edi, esi
	dec ecx
	jne jmp_10056c06
jmp_10056c42:
	jmp jmp_10057053
jmp_10056c47:
	mov eax, dword ptr p_parm
	push ebp
	mov ebp, ebx
	mov ebx, eax
jmp_10056c4f:
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	sub edi, esi
	dec ecx
	je jmp_10056c7f
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	sub edi, esi
	dec ecx
	je jmp_10056c7f
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	sub edi, esi
	dec ecx
	je jmp_10056c7f
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edx, ebp
	sub edi, esi
	dec ecx
	jne jmp_10056c4f
jmp_10056c7f:
	pop ebp
	jmp jmp_10057053
jmp_10056c85:
	mov esi, dword ptr p_pane
	mov edi, dword ptr l_unk0x24
	sub edi, dword ptr [esi+4]
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr [esi+8]
	mov esi, eax
	mov eax, dword ptr l_unk0x18
	add eax, eax
	inc eax
jmp_10056c9c:
	pushad
	call dword ptr p_parm
	popad
	add edx, ebx
	jae jmp_10056ca6
	dec edi
jmp_10056ca6:
	add esi, eax
	dec ecx
	jne jmp_10056c9c
	jmp jmp_10057053
jmp_10056cb0:
	mov eax, dword ptr l_unk0x2c
	sub eax, dword ptr l_unk0x24
	cdq
	xor eax, edx
	sub eax, edx
	inc eax
	mov ecx, eax
	mov eax, dword ptr l_unk0x24
	sub eax, dword ptr p_x0
	cdq
	xor eax, edx
	sub eax, edx
	mul ebx
	add eax, 80000000h
	mov edx, eax
	cmp dword ptr l_unk0x0c, -1
	je jmp_10056da9
	cmp dword ptr p_mode, 1
	je jmp_10056d2c
	jg jmp_10056d7e
	mov eax, dword ptr p_parm
jmp_10056ceb:
	mov word ptr [edi], ax
	add edi, 2
	add edx, ebx
	jae jmp_10056cf7
	add edi, esi
jmp_10056cf7:
	dec ecx
	je jmp_10056d27
	mov word ptr [edi], ax
	add edi, 2
	add edx, ebx
	jae jmp_10056d06
	add edi, esi
jmp_10056d06:
	dec ecx
	je jmp_10056d27
	mov word ptr [edi], ax
	add edi, 2
	add edx, ebx
	jae jmp_10056d15
	add edi, esi
jmp_10056d15:
	dec ecx
	je jmp_10056d27
	mov word ptr [edi], ax
	add edi, 2
	add edx, ebx
	jae jmp_10056d24
	add edi, esi
jmp_10056d24:
	dec ecx
	jne jmp_10056ceb
jmp_10056d27:
	jmp jmp_10057053
jmp_10056d2c:
	mov eax, dword ptr p_parm
	push ebp
	mov ebp, ebx
	mov ebx, eax
jmp_10056d34:
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, 2
	add edx, ebp
	jae jmp_10056d42
	add edi, esi
jmp_10056d42:
	dec ecx
	je jmp_10056d78
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, 2
	add edx, ebp
	jae jmp_10056d53
	add edi, esi
jmp_10056d53:
	dec ecx
	je jmp_10056d78
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, 2
	add edx, ebp
	jae jmp_10056d64
	add edi, esi
jmp_10056d64:
	dec ecx
	je jmp_10056d78
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, 2
	add edx, ebp
	jae jmp_10056d75
	add edi, esi
jmp_10056d75:
	dec ecx
	jne jmp_10056d34
jmp_10056d78:
	pop ebp
	jmp jmp_10057053
jmp_10056d7e:
	mov esi, dword ptr p_pane
	mov edi, dword ptr l_unk0x24
	sub edi, dword ptr [esi+4]
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr [esi+8]
	mov esi, eax
	mov eax, dword ptr l_unk0x18
	add eax, eax
	inc eax
jmp_10056d95:
	pushad
	call dword ptr p_parm
	popad
	add edx, ebx
	jae jmp_10056d9f
	inc esi
jmp_10056d9f:
	add edi, eax
	dec ecx
	jne jmp_10056d95
	jmp jmp_10057053
jmp_10056da9:
	cmp dword ptr p_mode, 1
	je jmp_10056df9
	jg jmp_10056e4b
	mov eax, dword ptr p_parm
jmp_10056db8:
	mov word ptr [edi], ax
	sub edi, 2
	add edx, ebx
	jae jmp_10056dc4
	add edi, esi
jmp_10056dc4:
	dec ecx
	je jmp_10056df4
	mov word ptr [edi], ax
	sub edi, 2
	add edx, ebx
	jae jmp_10056dd3
	add edi, esi
jmp_10056dd3:
	dec ecx
	je jmp_10056df4
	mov word ptr [edi], ax
	sub edi, 2
	add edx, ebx
	jae jmp_10056de2
	add edi, esi
jmp_10056de2:
	dec ecx
	je jmp_10056df4
	mov word ptr [edi], ax
	sub edi, 2
	add edx, ebx
	jae jmp_10056df1
	add edi, esi
jmp_10056df1:
	dec ecx
	jne jmp_10056db8
jmp_10056df4:
	jmp jmp_10057053
jmp_10056df9:
	mov eax, dword ptr p_parm
	push ebp
	mov ebp, ebx
	mov ebx, eax
jmp_10056e01:
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	sub edi, 2
	add edx, ebp
	jae jmp_10056e0f
	add edi, esi
jmp_10056e0f:
	dec ecx
	je jmp_10056e45
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	sub edi, 2
	add edx, ebp
	jae jmp_10056e20
	add edi, esi
jmp_10056e20:
	dec ecx
	je jmp_10056e45
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	sub edi, 2
	add edx, ebp
	jae jmp_10056e31
	add edi, esi
jmp_10056e31:
	dec ecx
	je jmp_10056e45
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	sub edi, 2
	add edx, ebp
	jae jmp_10056e42
	add edi, esi
jmp_10056e42:
	dec ecx
	jne jmp_10056e01
jmp_10056e45:
	pop ebp
	jmp jmp_10057053
jmp_10056e4b:
	mov esi, dword ptr p_pane
	mov edi, dword ptr l_unk0x24
	sub edi, dword ptr [esi+4]
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr [esi+8]
	mov esi, eax
	mov eax, dword ptr l_unk0x18
	add eax, eax
	inc eax
jmp_10056e62:
	pushad
	call dword ptr p_parm
	popad
	add edx, ebx
	jae jmp_10056e6c
	dec esi
jmp_10056e6c:
	add edi, eax
	dec ecx
	jne jmp_10056e62
	jmp jmp_10057053
jmp_10056e76:
	mov eax, dword ptr p_x0
	cmp eax, dword ptr l_unk0x3c
	jl jmp_10057062
	cmp eax, dword ptr l_unk0x44
	jg jmp_10057062
	mov eax, dword ptr p_y0
	cmp eax, dword ptr p_y1
	jg jmp_10056e96
	mov eax, dword ptr p_y1
jmp_10056e96:
	cmp eax, dword ptr l_unk0x40
	jl jmp_10057062
	mov eax, dword ptr p_y0
	cmp eax, dword ptr p_y1
	jl jmp_10056eaa
	mov eax, dword ptr p_y1
jmp_10056eaa:
	cmp eax, dword ptr l_unk0x48
	jg jmp_10057062
	mov eax, dword ptr p_y0
	cmp eax, dword ptr l_unk0x40
	jg jmp_10056ebe
	mov eax, dword ptr l_unk0x40
jmp_10056ebe:
	cmp eax, dword ptr l_unk0x48
	jl jmp_10056ec6
	mov eax, dword ptr l_unk0x48
jmp_10056ec6:
	mov dword ptr l_unk0x28, eax
	mov eax, dword ptr p_y1
	cmp eax, dword ptr l_unk0x40
	jg jmp_10056ed4
	mov eax, dword ptr l_unk0x40
jmp_10056ed4:
	cmp eax, dword ptr l_unk0x48
	jl jmp_10056edc
	mov eax, dword ptr l_unk0x48
jmp_10056edc:
	mov dword ptr l_unk0x30, eax
	mov eax, dword ptr p_x0
	mov dword ptr l_unk0x24, eax
	mov esi, dword ptr l_unk0x50
	xor esi, dword ptr l_unk0x18
	sub esi, dword ptr l_unk0x18
	mov eax, dword ptr l_unk0x30
	sub eax, dword ptr l_unk0x28
	cdq
	xor eax, edx
	sub eax, edx
	mov ecx, eax
	inc ecx
	jmp jmp_10056fab
jmp_10056f01:
	mov eax, dword ptr p_y0
	cmp eax, dword ptr l_unk0x40
	jl jmp_10057062
	cmp eax, dword ptr l_unk0x48
	jg jmp_10057062
	mov eax, dword ptr p_x0
	cmp eax, dword ptr p_x1
	jg jmp_10056f21
	mov eax, dword ptr p_x1
jmp_10056f21:
	cmp eax, dword ptr l_unk0x3c
	jl jmp_10057062
	mov eax, dword ptr p_x0
	cmp eax, dword ptr p_x1
	jl jmp_10056f35
	mov eax, dword ptr p_x1
jmp_10056f35:
	cmp eax, dword ptr l_unk0x44
	jg jmp_10057062
	mov eax, dword ptr p_x0
	cmp eax, dword ptr l_unk0x3c
	jg jmp_10056f49
	mov eax, dword ptr l_unk0x3c
jmp_10056f49:
	cmp eax, dword ptr l_unk0x44
	jl jmp_10056f51
	mov eax, dword ptr l_unk0x44
jmp_10056f51:
	mov dword ptr l_unk0x24, eax
	mov eax, dword ptr p_x1
	cmp eax, dword ptr l_unk0x3c
	jg jmp_10056f5f
	mov eax, dword ptr l_unk0x3c
jmp_10056f5f:
	cmp eax, dword ptr l_unk0x44
	jl jmp_10056f67
	mov eax, dword ptr l_unk0x44
jmp_10056f67:
	mov dword ptr l_unk0x2c, eax
	mov eax, dword ptr p_y0
	mov dword ptr l_unk0x28, eax
	mov esi, dword ptr l_unk0x0c
	inc esi
	or esi, dword ptr l_unk0x0c
	shl esi, 1
	mov eax, dword ptr l_unk0x2c
	sub eax, dword ptr l_unk0x24
	cdq
	xor eax, edx
	sub eax, edx
	mov ecx, eax
	inc ecx
	jmp jmp_10056fab
jmp_10056f89:
	mov esi, dword ptr l_unk0x50
	xor esi, dword ptr l_unk0x18
	sub esi, dword ptr l_unk0x18
	mov eax, dword ptr l_unk0x0c
	inc eax
	or eax, dword ptr l_unk0x0c
	shl eax, 1
	add esi, eax
	mov eax, dword ptr l_unk0x2c
	sub eax, dword ptr l_unk0x24
	cdq
	xor eax, edx
	sub eax, edx
	mov ecx, eax
	inc ecx
jmp_10056fab:
	mov eax, dword ptr l_unk0x28
	imul dword ptr l_unk0x50
	add eax, dword ptr l_unk0x24
	add eax, dword ptr l_unk0x24
	add eax, dword ptr l_unk0x4c
	mov edi, eax
	cmp dword ptr p_mode, 1
	je jmp_10056fe9
	jg jmp_10057016
	mov eax, dword ptr p_parm
jmp_10056fc7:
	mov word ptr [edi], ax
	add edi, esi
	dec ecx
	je jmp_10056fe7
	mov word ptr [edi], ax
	add edi, esi
	dec ecx
	je jmp_10056fe7
	mov word ptr [edi], ax
	add edi, esi
	dec ecx
	je jmp_10056fe7
	mov word ptr [edi], ax
	add edi, esi
	dec ecx
	jne jmp_10056fc7
jmp_10056fe7:
	jmp jmp_10057053
jmp_10056fe9:
	mov ebx, dword ptr p_parm
jmp_10056fec:
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, esi
	dec ecx
	je jmp_10057014
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, esi
	dec ecx
	je jmp_10057014
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, esi
	dec ecx
	je jmp_10057014
	mov al, byte ptr [edi]
	xlatb
	mov byte ptr [edi], al
	add edi, esi
	dec ecx
	jne jmp_10056fec
jmp_10057014:
	jmp jmp_10057053
jmp_10057016:
	mov esi, dword ptr p_pane
	mov edi, dword ptr l_unk0x24
	sub edi, dword ptr [esi+4]
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr [esi+8]
	mov esi, eax
	xor eax, eax
	test dword ptr l_unk0x10, 0ffffffffh
	setne al
	or eax, dword ptr l_unk0x18
	xor ebx, ebx
	test dword ptr l_unk0x04, 0ffffffffh
	setne bl
	or ebx, dword ptr l_unk0x0c
jmp_10057045:
	pushad
	call dword ptr p_parm
	popad
	add esi, eax
	add edi, ebx
	dec ecx
	jne jmp_10057045
	jmp jmp_10057053
jmp_10057053:
	xor eax, eax
	cmp dword ptr l_unk0x34, 1
	setae al
	pop es
	ret
jmp_10057062:
	mov eax, 2
	pop es
	ret
VFX_line_draw16 endp

; VFXA's VFX_shape_lookaside, for a table of 16-bit pixels (0x200 bytes).
VFX_shape_lookaside16 proc uses ebx esi edi, p_table:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_table
	mov edi, offset lookaside16
	mov ecx, 80h
	rep movsd
	pop es
	ret
VFX_shape_lookaside16 endp

; The port's own: sets the 16-bit pixel of one color in the lookaside table. The game sets the table
; from the palette with it (palette.c).
VFX_lookaside_write16 proc uses ebx esi edi, p_index:dword, p_pixel:dword
	push es
	cld
	push ds
	pop es
	mov eax, dword ptr p_index
	mov ebx, dword ptr p_pixel
	mov word ptr [lookaside16+eax*2], bx
	pop es
	ret
VFX_lookaside_write16 endp

; The port's own: the 16-bit pixel of a color, from the lookaside table, in ax (the game's
; PIXEL_COLOR, palette.h).
VFX_lookaside_read16 proc uses ebx esi edi, p_color:dword
	push es
	cld
	push ds
	pop es
	mov eax, dword ptr p_color
	mov ax, word ptr [lookaside16+eax*2]
	pop es
	ret
VFX_lookaside_read16 endp

; VFXA's VFX_shape_draw, drawing a shape's 8-bit colors as their lookaside pixels.
VFX_shape_draw16 proc uses ebx esi edi, p_pane:dword, p_shapeTable:dword, p_shapeNumber:dword, p_hotX:dword, p_hotY:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword, l_unk0x28:dword, l_unk0x2c:dword, l_unk0x30:dword
	local l_unk0x34:dword, l_unk0x38:dword, l_unk0x3c:dword, l_unk0x40:dword, l_unk0x44:dword, l_unk0x48:dword
	local l_unk0x4c:dword, l_unk0x50:dword, l_unk0x54:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x48, eax
	jle jmp_10057149
	shl eax, 1
	mov dword ptr l_unk0x4c, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_10057149
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x50, eax
	cmp eax, 0
	jg jmp_100570fd
	mov eax, 0
jmp_100570fd:
	mov dword ptr l_unk0x34, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x54, eax
	cmp eax, 0
	jg jmp_10057110
	mov eax, 0
jmp_10057110:
	mov dword ptr l_unk0x38, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x48
	dec edx
	cmp eax, edx
	jl jmp_10057120
	mov eax, edx
jmp_10057120:
	mov dword ptr l_unk0x3c, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_1005712f
	mov eax, edx
jmp_1005712f:
	mov dword ptr l_unk0x40, eax
	mov eax, dword ptr l_unk0x3c
	cmp eax, dword ptr l_unk0x34
	jl jmp_10057154
	mov eax, dword ptr l_unk0x40
	cmp eax, dword ptr l_unk0x38
	jl jmp_10057154
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x44, eax
	jmp jmp_1005715f
jmp_10057149:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_10057154:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_1005715f:
	mov eax, dword ptr l_unk0x50
	add dword ptr p_hotX, eax
	mov eax, dword ptr l_unk0x54
	add dword ptr p_hotY, eax
	mov esi, dword ptr p_shapeNumber
	shl esi, 3
	add esi, 8
	add esi, dword ptr p_shapeTable
	mov esi, dword ptr [esi]
	add esi, dword ptr p_shapeTable
	mov dword ptr l_unk0x30, esi
	mov eax, dword ptr [esi+8]
	add eax, dword ptr p_hotX
	mov dword ptr l_unk0x0c, eax
	mov eax, dword ptr [esi+0ch]
	add eax, dword ptr p_hotY
	mov dword ptr l_unk0x10, eax
	mov eax, dword ptr [esi+10h]
	add eax, dword ptr p_hotX
	mov dword ptr l_unk0x14, eax
	mov eax, dword ptr [esi+14h]
	add eax, dword ptr p_hotY
	mov dword ptr l_unk0x18, eax
	add esi, 18h
	mov eax, dword ptr l_unk0x14
	cmp eax, dword ptr l_unk0x0c
	jl jmp_100575dc
	mov eax, dword ptr l_unk0x18
	cmp eax, dword ptr l_unk0x10
	jl jmp_100575dc
	xor edx, edx
	mov eax, dword ptr l_unk0x0c
	sub eax, dword ptr l_unk0x34
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x3c
	sub eax, dword ptr l_unk0x0c
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x10
	sub eax, dword ptr l_unk0x38
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x40
	sub eax, dword ptr l_unk0x10
	shl eax, 1
	adc dl, dl
	mov eax, dword ptr l_unk0x14
	sub eax, dword ptr l_unk0x34
	shl eax, 1
	adc dh, dh
	mov eax, dword ptr l_unk0x3c
	sub eax, dword ptr l_unk0x14
	shl eax, 1
	adc dh, dh
	mov eax, dword ptr l_unk0x18
	sub eax, dword ptr l_unk0x38
	shl eax, 1
	adc dh, dh
	mov eax, dword ptr l_unk0x40
	sub eax, dword ptr l_unk0x18
	shl eax, 1
	adc dh, dh
	mov dword ptr l_unk0x1c, edx
	test dl, dh
	jne jmp_100575d1
	or dl, dh
	jne jmp_1005724a
	mov esi, dword ptr p_pane
	mov eax, dword ptr [esi+4]
	sub dword ptr p_hotX, eax
	mov eax, dword ptr [esi+8]
	sub dword ptr p_hotY, eax
	push dword ptr l_unk0x48
	push dword ptr p_hotY
	push dword ptr p_hotX
	push dword ptr l_unk0x30
	push dword ptr p_pane
	call DrawShapeUnclipped16
	add esp, 14h
	jmp jmp_100575c9
jmp_1005724a:
	mov eax, dword ptr l_unk0x10
	imul dword ptr l_unk0x48
	add eax, dword ptr l_unk0x0c
	add eax, dword ptr l_unk0x0c
	add eax, dword ptr l_unk0x44
	mov edi, eax
	mov ecx, dword ptr l_unk0x10
	mov dword ptr l_unk0x20, ecx
	jmp jmp_10057279
jmp_10057263:
	movzx eax, al
	add esi, eax
	dec esi
jmp_10057269:
	inc esi
jmp_1005726a:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057269
	jne jmp_10057263
	jb jmp_10057269
	add edi, dword ptr l_unk0x48
	inc ecx
jmp_10057279:
	cmp ecx, dword ptr l_unk0x38
	jl jmp_1005726a
	mov dword ptr l_unk0x24, edi
	mov dword ptr l_unk0x20, ecx
	mov eax, dword ptr l_unk0x34
	sub eax, dword ptr l_unk0x0c
	shl eax, 1
	add eax, edi
	mov dword ptr l_unk0x28, eax
	mov eax, dword ptr l_unk0x3c
	sub eax, dword ptr l_unk0x0c
	shl eax, 1
	add eax, edi
	mov dword ptr l_unk0x2c, eax
	jmp jmp_100575bd
jmp_100572a3:
	mov eax, dword ptr l_unk0x20
	cmp eax, dword ptr l_unk0x40
	jg jmp_100575c9
	mov edi, dword ptr l_unk0x24
	test dword ptr l_unk0x1c, 8
	jne jmp_100573a1
	test dword ptr l_unk0x1c, 400h
	jne jmp_10057449
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100572f6
	jne jmp_10057318
	jae jmp_1005739c
jmp_100572db:
	mov al, byte ptr [esi]
	inc esi
	movzx ecx, al
	add edi, ecx
	add edi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100572f6
	jne jmp_10057318
	jb jmp_100572db
	jae jmp_1005739c
jmp_100572f6:
	movzx ecx, al
jmp_100572f9:
	xor eax, eax
	mov al, byte ptr [esi]
	inc esi
	mov ax, word ptr [lookaside16+eax*2]
	rep stosw
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100572f6
	jae jmp_1005739c
	je jmp_100572db
jmp_10057318:
	movzx ecx, al
jmp_1005731b:
	xor eax, eax
	or ecx, ecx
	je jmp_10057389
	cmp ecx, 4
	jl jmp_10057374
jmp_10057326:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi], ax
	movzx eax, byte ptr [esi+1]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+2], ax
	movzx eax, byte ptr [esi+2]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+4], ax
	movzx eax, byte ptr [esi+3]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+6], ax
	add esi, 4
	add edi, 8
	sub ecx, 4
	je jmp_10057389
	cmp ecx, 4
	jge jmp_10057326
jmp_10057374:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi], ax
	inc esi
	add edi, 2
	dec ecx
	jne jmp_10057374
jmp_10057389:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100572f6
	jne jmp_10057318
	jb jmp_100572db
jmp_1005739c:
	jmp jmp_100575ae
jmp_100573a1:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100573c7
	jne jmp_10057402
	jae jmp_10057444
jmp_100573b0:
	mov al, byte ptr [esi]
	inc esi
	movzx ecx, al
	add edi, ecx
	add edi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100573c7
	jne jmp_10057402
	jb jmp_100573b0
	jae jmp_10057444
jmp_100573c7:
	movzx ecx, al
	mov eax, dword ptr l_unk0x28
	sub eax, edi
	sar eax, 1
	cmp eax, ecx
	jge jmp_100573f2
	or eax, eax
	js jmp_100573df
	add edi, eax
	add edi, eax
	sub ecx, eax
jmp_100573df:
	test dword ptr l_unk0x1c, 400h
	je jmp_100572f9
	jne jmp_10057476
jmp_100573f2:
	add edi, ecx
	add edi, ecx
	inc esi
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100573c7
	jae jmp_10057444
	je jmp_100573b0
jmp_10057402:
	movzx ecx, al
	mov eax, dword ptr l_unk0x28
	sub eax, edi
	sar eax, 1
	cmp eax, ecx
	jge jmp_1005742f
	or eax, eax
	js jmp_1005741c
	add edi, eax
	add edi, eax
	sub ecx, eax
	add esi, eax
jmp_1005741c:
	test dword ptr l_unk0x1c, 400h
	je jmp_1005731b
	jne jmp_100574ba
jmp_1005742f:
	add edi, ecx
	add edi, ecx
	add esi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100573c7
	jne jmp_10057402
	jb jmp_100573b0
jmp_10057444:
	jmp jmp_100575ae
jmp_10057449:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057473
	jne jmp_100574b7
	jae jmp_10057563
jmp_10057458:
	mov al, byte ptr [esi]
	inc esi
	movzx ecx, al
	add edi, ecx
	add edi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057473
	jne jmp_100574b7
	jb jmp_10057458
	jae jmp_10057563
jmp_10057473:
	movzx ecx, al
jmp_10057476:
	cmp edi, dword ptr l_unk0x2c
	jg jmp_1005758a
	mov eax, edi
	add eax, ecx
	add eax, ecx
	sub eax, 2
	sub eax, dword ptr l_unk0x2c
	cdq
	not edx
	and edx, eax
	shr edx, 1
	sub ecx, edx
	xor eax, eax
	mov al, byte ptr [esi]
	inc esi
	mov ax, word ptr [lookaside16+eax*2]
	rep stosw
	add edi, edx
	add edi, edx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057473
	jae jmp_10057563
	je jmp_10057458
jmp_100574b7:
	movzx ecx, al
jmp_100574ba:
	cmp edi, dword ptr l_unk0x2c
	jg jmp_1005759d
	mov eax, edi
	add eax, ecx
	add eax, ecx
	sub eax, 2
	sub eax, dword ptr l_unk0x2c
	cdq
	not edx
	and edx, eax
	shr edx, 1
	sub ecx, edx
	xor eax, eax
	or ecx, ecx
	je jmp_10057546
	cmp ecx, 4
	jl jmp_10057531
jmp_100574e3:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi], ax
	movzx eax, byte ptr [esi+1]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+2], ax
	movzx eax, byte ptr [esi+2]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+4], ax
	movzx eax, byte ptr [esi+3]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+6], ax
	add esi, 4
	add edi, 8
	sub ecx, 4
	je jmp_10057546
	cmp ecx, 4
	jge jmp_100574e3
jmp_10057531:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi], ax
	inc esi
	add edi, 2
	dec ecx
	jne jmp_10057531
jmp_10057546:
	add edi, edx
	add edi, edx
	add esi, edx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057473
	jne jmp_100574b7
	jb jmp_10057458
jmp_10057563:
	jmp jmp_100575ae
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057587
	jne jmp_1005759a
	jae jmp_100575ae
jmp_10057570:
	mov al, byte ptr [esi]
	inc esi
	movzx ecx, al
	add edi, ecx
	add edi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057587
	jne jmp_1005759a
	jb jmp_10057570
	jae jmp_100575ae
jmp_10057587:
	movzx ecx, al
jmp_1005758a:
	add edi, ecx
	add edi, ecx
	inc esi
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057587
	jae jmp_100575ae
	je jmp_10057570
jmp_1005759a:
	movzx ecx, al
jmp_1005759d:
	add edi, ecx
	add edi, ecx
	add esi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_10057587
	jne jmp_1005759a
	jb jmp_10057570
jmp_100575ae:
	mov eax, dword ptr l_unk0x48
	add dword ptr l_unk0x24, eax
	add dword ptr l_unk0x28, eax
	add dword ptr l_unk0x2c, eax
	inc dword ptr l_unk0x20
jmp_100575bd:
	mov eax, dword ptr l_unk0x20
	cmp eax, dword ptr l_unk0x18
	jle jmp_100572a3
jmp_100575c9:
	xor eax, eax
	pop es
	ret
jmp_100575d1:
	mov eax, 0fffffffdh
	pop es
	ret
jmp_100575dc:
	mov eax, 0fffffffch
	pop es
	ret
VFX_shape_draw16 endp

; VFXA's DrawShapeUnclipped, VFX_shape_draw16's unclipped case.
DrawShapeUnclipped16 proc uses ebx esi edi, p_pane:dword, p_shape:dword, p_hotX:dword, p_hotY:dword, p_cpW:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [esi+4]
	add dword ptr p_hotX, eax
	mov eax, dword ptr [esi+8]
	add dword ptr p_hotY, eax
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr p_cpW, eax
	jle jmp_1005771d
	mov esi, dword ptr p_shape
	mov edi, dword ptr [ebx]
	mov eax, dword ptr [esi+8]
	add eax, dword ptr p_hotX
	add edi, eax
	add edi, eax
	mov eax, dword ptr [esi+0ch]
	mov ebx, eax
	add eax, dword ptr p_hotY
	mul dword ptr p_cpW
	add edi, eax
	mov edx, edi
	mov eax, dword ptr [esi+10h]
	mov eax, dword ptr [esi+14h]
	inc eax
	sub eax, ebx
	mov ebx, eax
	jle jmp_1005771d
	add esi, 18h
jmp_10057641:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_1005766b
	jne jmp_1005768d
	jae jmp_10057711
jmp_10057650:
	mov al, byte ptr [esi]
	inc esi
	movzx ecx, al
	add edi, ecx
	add edi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_1005766b
	jne jmp_1005768d
	jb jmp_10057650
	jae jmp_10057711
jmp_1005766b:
	movzx ecx, al
	xor eax, eax
	mov al, byte ptr [esi]
	inc esi
	mov ax, word ptr [lookaside16+eax*2]
	rep stosw
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_1005766b
	jae jmp_10057711
	je jmp_10057650
jmp_1005768d:
	movzx ecx, al
	xor eax, eax
	or ecx, ecx
	je jmp_100576fe
	cmp ecx, 4
	jl jmp_100576e9
jmp_1005769b:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi], ax
	movzx eax, byte ptr [esi+1]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+2], ax
	movzx eax, byte ptr [esi+2]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+4], ax
	movzx eax, byte ptr [esi+3]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi+6], ax
	add esi, 4
	add edi, 8
	sub ecx, 4
	je jmp_100576fe
	cmp ecx, 4
	jge jmp_1005769b
jmp_100576e9:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [lookaside16+eax*2]
	mov word ptr [edi], ax
	inc esi
	add edi, 2
	dec ecx
	jne jmp_100576e9
jmp_100576fe:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_1005766b
	jne jmp_1005768d
	jb jmp_10057650
jmp_10057711:
	add edx, dword ptr p_cpW
	mov edi, edx
	dec ebx
	jne jmp_10057641
jmp_1005771d:
	xor eax, eax
	pop es
	ret
DrawShapeUnclipped16 endp

; VFXA's VFX_shape_visible_rectangle (no pixels: nearly unchanged).
VFX_shape_visible_rectangle16 proc uses ebx esi edi, p_shapeTable:dword, p_shapeNumber:dword, p_hotX:dword, p_hotY:dword, p_mirror:dword, p_rectangle:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword
	push es
	cld
	push ds
	pop es
	mov dword ptr l_unk0x18, 0
	mov dword ptr l_unk0x1c, 0
	mov dword ptr l_unk0x20, 0
	mov dword ptr l_unk0x24, 0
	mov esi, dword ptr p_shapeNumber
	shl esi, 3
	add esi, 8
	add esi, dword ptr p_shapeTable
	mov esi, dword ptr [esi]
	add esi, dword ptr p_shapeTable
	mov dword ptr l_unk0x04, esi
	mov esi, dword ptr l_unk0x04
	mov eax, dword ptr [esi+8]
	add eax, dword ptr p_hotX
	mov dword ptr l_unk0x08, eax
	mov eax, dword ptr [esi+0ch]
	mov ebx, eax
	add eax, dword ptr p_hotY
	mov dword ptr l_unk0x0c, eax
	mov eax, dword ptr [esi+10h]
	add eax, dword ptr p_hotX
	mov dword ptr l_unk0x10, eax
	mov eax, dword ptr [esi+14h]
	mov ecx, eax
	add ecx, dword ptr p_hotY
	mov dword ptr l_unk0x14, ecx
	inc eax
	sub eax, ebx
	mov ebx, eax
	jle jmp_1005784a
	add esi, 18h
	mov dword ptr l_unk0x18, 7fffffffh
	mov dword ptr l_unk0x1c, 7fffffffh
	mov dword ptr l_unk0x20, 80000000h
	mov dword ptr l_unk0x24, 80000000h
	mov edx, dword ptr l_unk0x0c
jmp_100577ba:
	mov edi, dword ptr l_unk0x08
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100577dd
	jne jmp_10057810
	jae jmp_10057842
jmp_100577c8:
	mov al, byte ptr [esi]
	inc esi
	movzx ecx, al
	add edi, ecx
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100577dd
	jne jmp_10057810
	jb jmp_100577c8
	jae jmp_10057842
jmp_100577dd:
	movzx ecx, al
	mov al, byte ptr [esi]
	inc esi
	cmp dword ptr l_unk0x18, edi
	jl jmp_100577eb
	mov dword ptr l_unk0x18, edi
jmp_100577eb:
	add edi, ecx
	cmp dword ptr l_unk0x20, edi
	jg jmp_100577f5
	mov dword ptr l_unk0x20, edi
jmp_100577f5:
	cmp dword ptr l_unk0x1c, edx
	jl jmp_100577fd
	mov dword ptr l_unk0x1c, edx
jmp_100577fd:
	cmp dword ptr l_unk0x24, edx
	jg jmp_10057805
	mov dword ptr l_unk0x24, edx
jmp_10057805:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100577dd
	jae jmp_10057842
	je jmp_100577c8
jmp_10057810:
	movzx ecx, al
	add esi, ecx
	cmp dword ptr l_unk0x18, edi
	jl jmp_1005781d
	mov dword ptr l_unk0x18, edi
jmp_1005781d:
	add edi, ecx
	cmp dword ptr l_unk0x20, edi
	jg jmp_10057827
	mov dword ptr l_unk0x20, edi
jmp_10057827:
	cmp dword ptr l_unk0x1c, edx
	jl jmp_1005782f
	mov dword ptr l_unk0x1c, edx
jmp_1005782f:
	cmp dword ptr l_unk0x24, edx
	jg jmp_10057837
	mov dword ptr l_unk0x24, edx
jmp_10057837:
	mov al, byte ptr [esi]
	inc esi
	shr al, 1
	ja jmp_100577dd
	jne jmp_10057810
	jb jmp_100577c8
jmp_10057842:
	inc edx
	dec ebx
	jne jmp_100577ba
jmp_1005784a:
	mov eax, dword ptr p_mirror
	and eax, 1
	je jmp_10057866
	mov eax, dword ptr p_hotX
	add eax, dword ptr p_hotX
	mov ebx, eax
	sub eax, dword ptr l_unk0x18
	sub ebx, dword ptr l_unk0x20
	mov dword ptr l_unk0x20, eax
	mov dword ptr l_unk0x18, ebx
jmp_10057866:
	mov eax, dword ptr p_mirror
	and eax, 2
	je jmp_10057882
	mov eax, dword ptr p_hotY
	add eax, dword ptr p_hotY
	mov ebx, eax
	sub eax, dword ptr l_unk0x1c
	sub ebx, dword ptr l_unk0x24
	mov dword ptr l_unk0x24, eax
	mov dword ptr l_unk0x1c, ebx
jmp_10057882:
	mov edi, dword ptr p_rectangle
	mov eax, dword ptr l_unk0x18
	stosd
	mov eax, dword ptr l_unk0x1c
	stosd
	mov eax, dword ptr l_unk0x20
	stosd
	mov eax, dword ptr l_unk0x24
	stosd
	xor eax, eax
	pop es
	ret
VFX_shape_visible_rectangle16 endp

; VFXA's VFX_pane_wipe, filling with a 16-bit pixel.
VFX_pane_wipe16 proc uses ebx esi edi, p_pane:dword, p_color:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x1c, eax
	jle jmp_10057921
	shl eax, 1
	mov dword ptr l_unk0x18, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_10057921
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x20, eax
	cmp eax, 0
	jg jmp_100578d5
	mov eax, 0
jmp_100578d5:
	mov dword ptr l_unk0x04, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x24, eax
	cmp eax, 0
	jg jmp_100578e8
	mov eax, 0
jmp_100578e8:
	mov dword ptr l_unk0x08, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x1c
	dec edx
	cmp eax, edx
	jl jmp_100578f8
	mov eax, edx
jmp_100578f8:
	mov dword ptr l_unk0x0c, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_10057907
	mov eax, edx
jmp_10057907:
	mov dword ptr l_unk0x10, eax
	mov eax, dword ptr l_unk0x0c
	cmp eax, dword ptr l_unk0x04
	jl jmp_1005792c
	mov eax, dword ptr l_unk0x10
	cmp eax, dword ptr l_unk0x08
	jl jmp_1005792c
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x14, eax
	jmp jmp_10057937
jmp_10057921:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_1005792c:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_10057937:
	mov eax, dword ptr l_unk0x08
	imul dword ptr l_unk0x1c
	add eax, dword ptr l_unk0x04
	add eax, dword ptr l_unk0x04
	add eax, dword ptr l_unk0x14
	mov edi, eax
	mov ebx, dword ptr l_unk0x0c
	inc ebx
	sub ebx, dword ptr l_unk0x04
	mov esi, dword ptr l_unk0x1c
	shl ebx, 1
	sub esi, ebx
	shr ebx, 1
	mov ax, word ptr p_color
	shl eax, 10h
	mov ax, word ptr p_color
	mov edx, dword ptr l_unk0x08
	jmp jmp_10057979
jmp_10057968:
	mov ecx, ebx
	and ecx, 1
	rep stosw
	mov ecx, ebx
	shr ecx, 1
	rep stosd
	add edi, esi
	inc edx
jmp_10057979:
	cmp edx, dword ptr l_unk0x10
	jle jmp_10057968
	xor eax, eax
	pop es
	ret
VFX_pane_wipe16 endp

; VFXA's VFX_ellipse_draw, plotting 16-bit pixels.
VFX_ellipse_draw16 proc uses ebx esi edi, p_pane:dword, p_xc:dword, p_yc:dword, p_width:dword, p_height:dword, p_color:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword, l_unk0x28:dword, l_unk0x2c:dword, l_unk0x30:dword
	local l_unk0x34:dword, l_unk0x38:dword, l_unk0x3c:dword, l_unk0x40:dword, l_unk0x44:dword, l_unk0x48:dword
	local l_unk0x4c:dword, l_unk0x50:dword, l_unk0x54:dword, l_unk0x58:dword
	push es
	cld
	push ds
	pop es
	cmp dword ptr p_width, 0
	je jmp_1005799f
	cmp dword ptr p_height, 0
	jne jmp_100579d0
jmp_1005799f:
	mov eax, dword ptr p_yc
	add eax, dword ptr p_height
	mov ebx, dword ptr p_xc
	add ebx, dword ptr p_width
	mov ecx, dword ptr p_yc
	sub ecx, dword ptr p_height
	mov edx, dword ptr p_xc
	sub edx, dword ptr p_width
	push dword ptr p_color
	push 0
	push eax
	push ebx
	push ecx
	push edx
	push dword ptr p_pane
	call VFX_line_draw16
	add esp, 1ch
	jmp jmp_10057cd9
jmp_100579d0:
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x4c, eax
	jle jmp_10057a47
	shl eax, 1
	mov dword ptr l_unk0x50, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_10057a47
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x54, eax
	cmp eax, 0
	jg jmp_100579fb
	mov eax, 0
jmp_100579fb:
	mov dword ptr l_unk0x38, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x58, eax
	cmp eax, 0
	jg jmp_10057a0e
	mov eax, 0
jmp_10057a0e:
	mov dword ptr l_unk0x3c, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x4c
	dec edx
	cmp eax, edx
	jl jmp_10057a1e
	mov eax, edx
jmp_10057a1e:
	mov dword ptr l_unk0x40, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_10057a2d
	mov eax, edx
jmp_10057a2d:
	mov dword ptr l_unk0x44, eax
	mov eax, dword ptr l_unk0x40
	cmp eax, dword ptr l_unk0x38
	jl jmp_10057a52
	mov eax, dword ptr l_unk0x44
	cmp eax, dword ptr l_unk0x3c
	jl jmp_10057a52
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x48, eax
	jmp jmp_10057a5d
jmp_10057a47:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_10057a52:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_10057a5d:
	mov eax, dword ptr p_color
	mov word ptr [ebp+1eh], ax
	mov eax, dword ptr l_unk0x54
	add dword ptr p_xc, eax
	mov eax, dword ptr l_unk0x58
	add dword ptr p_yc, eax
	mov eax, dword ptr p_xc
	mov dword ptr l_unk0x04, eax
	mov eax, dword ptr p_yc
	mov dword ptr l_unk0x08, eax
	mov dword ptr l_unk0x0c, 0
	mov eax, dword ptr p_height
	mov dword ptr l_unk0x10, eax
	mul eax
	mov dword ptr l_unk0x1c, eax
	shl eax, 1
	mov dword ptr l_unk0x20, eax
	mov eax, dword ptr p_width
	mul eax
	mov dword ptr l_unk0x14, eax
	shl eax, 1
	mov dword ptr l_unk0x18, eax
	mov dword ptr l_unk0x24, 0
	mov eax, dword ptr l_unk0x18
	mul dword ptr p_height
	mov dword ptr l_unk0x28, eax
	mov eax, dword ptr l_unk0x14
	shr eax, 2
	add eax, dword ptr l_unk0x1c
	mov dword ptr l_unk0x2c, eax
	mov eax, dword ptr l_unk0x14
	mul dword ptr p_height
	sub dword ptr l_unk0x2c, eax
	mov ebx, dword ptr p_height
jmp_10057ac8:
	mov eax, dword ptr l_unk0x24
	sub eax, dword ptr l_unk0x28
	jns jmp_10057bca
	push ebx
	mov ecx, dword ptr p_color
	mov edi, dword ptr l_unk0x04
	add edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	add edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057b09
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057b09
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057b09
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057b09
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057b09:
	mov edi, dword ptr l_unk0x04
	add edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	sub edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057b3a
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057b3a
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057b3a
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057b3a
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057b3a:
	mov edi, dword ptr l_unk0x04
	sub edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	add edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057b6b
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057b6b
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057b6b
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057b6b
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057b6b:
	mov edi, dword ptr l_unk0x04
	sub edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	sub edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057b9c
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057b9c
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057b9c
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057b9c
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057b9c:
	pop ebx
	cmp dword ptr l_unk0x2c, 0
	js jmp_10057bb3
	dec dword ptr l_unk0x10
	dec ebx
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr l_unk0x18
	mov dword ptr l_unk0x28, eax
	sub dword ptr l_unk0x2c, eax
jmp_10057bb3:
	inc dword ptr l_unk0x0c
	mov eax, dword ptr l_unk0x24
	add eax, dword ptr l_unk0x20
	mov dword ptr l_unk0x24, eax
	add eax, dword ptr l_unk0x1c
	add dword ptr l_unk0x2c, eax
	jmp jmp_10057ac8
jmp_10057bca:
	mov eax, dword ptr l_unk0x14
	sub eax, dword ptr l_unk0x1c
	mov edx, eax
	sar eax, 1
	add eax, edx
	sub eax, dword ptr l_unk0x24
	sub eax, dword ptr l_unk0x28
	sar eax, 1
	add dword ptr l_unk0x2c, eax
jmp_10057be1:
	push ebx
	mov ecx, dword ptr p_color
	mov edi, dword ptr l_unk0x04
	add edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	add edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057c16
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057c16
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057c16
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057c16
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057c16:
	mov edi, dword ptr l_unk0x04
	add edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	sub edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057c47
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057c47
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057c47
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057c47
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057c47:
	mov edi, dword ptr l_unk0x04
	sub edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	add edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057c78
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057c78
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057c78
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057c78
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057c78:
	mov edi, dword ptr l_unk0x04
	sub edi, dword ptr l_unk0x0c
	mov edx, dword ptr l_unk0x08
	sub edx, dword ptr l_unk0x10
	cmp edi, dword ptr l_unk0x38
	jl jmp_10057ca9
	cmp edi, dword ptr l_unk0x40
	jg jmp_10057ca9
	cmp edx, dword ptr l_unk0x3c
	jl jmp_10057ca9
	cmp edx, dword ptr l_unk0x44
	jg jmp_10057ca9
	mov eax, edx
	imul dword ptr l_unk0x4c
	add eax, edi
	add eax, edi
	add eax, dword ptr l_unk0x48
	mov edi, eax
	mov word ptr [edi], cx
jmp_10057ca9:
	pop ebx
	cmp dword ptr l_unk0x2c, 0
	jns jmp_10057cbf
	inc dword ptr l_unk0x0c
	mov eax, dword ptr l_unk0x24
	add eax, dword ptr l_unk0x20
	mov dword ptr l_unk0x24, eax
	add dword ptr l_unk0x2c, eax
jmp_10057cbf:
	dec dword ptr l_unk0x10
	mov eax, dword ptr l_unk0x28
	sub eax, dword ptr l_unk0x18
	mov dword ptr l_unk0x28, eax
	sub eax, dword ptr l_unk0x14
	sub dword ptr l_unk0x2c, eax
	dec ebx
	js jmp_10057cd9
	jmp jmp_10057be1
jmp_10057cd9:
	pop es
	ret
VFX_ellipse_draw16 endp

; VFX_Cos_Sin16's cosine table: VFXA's CosTable, one 16.16 entry per tenth of a degree from 0 to 90.
	public CosTable16
CosTable16_t struct
m_data dd 3 dup (10000h), 0ffffh, 0fffeh, 0fffeh, 0fffch, 0fffbh, 0fffah, 0fff8h, 0fff6h, 0fff4h
	dd 0fff2h, 0ffefh, 0ffech, 0ffeah, 0ffe6h, 0ffe3h, 0ffe0h, 0ffdch, 0ffd8h, 0ffd4h, 0ffd0h
	dd 0ffcbh, 0ffc7h, 0ffc2h, 0ffbdh, 0ffb7h, 0ffb2h, 0ffach, 0ffa6h, 0ffa0h, 0ff9ah, 0ff93h
	dd 0ff8dh, 0ff86h, 0ff7fh, 0ff77h, 0ff70h, 0ff68h, 0ff60h, 0ff58h, 0ff50h, 0ff48h, 0ff3fh
	dd 0ff36h, 0ff2dh, 0ff24h, 0ff1ah, 0ff10h, 0ff07h, 0fefdh, 0fef2h, 0fee8h, 0feddh, 0fed2h
	dd 0fec7h, 0febch, 0feb1h, 0fea5h, 0fe99h, 0fe8dh, 0fe81h, 0fe74h, 0fe68h, 0fe5bh, 0fe4eh
	dd 0fe40h, 0fe33h, 0fe25h, 0fe18h, 0fe09h, 0fdfbh, 0fdedh, 0fddeh, 0fdcfh, 0fdc0h, 0fdb1h
	dd 0fda2h, 0fd92h, 0fd82h, 0fd72h, 0fd62h, 0fd52h, 0fd41h, 0fd30h, 0fd1fh, 0fd0eh, 0fcfdh
	dd 0fcebh, 0fcd9h, 0fcc7h, 0fcb5h, 0fca3h, 0fc90h, 0fc7dh, 0fc6ah, 0fc57h, 0fc44h, 0fc30h
	dd 0fc1ch, 0fc08h, 0fbf4h, 0fbe0h, 0fbcbh, 0fbb7h, 0fba2h, 0fb8dh, 0fb77h, 0fb62h, 0fb4ch
	dd 0fb36h, 0fb20h, 0fb0ah, 0faf3h, 0fadch, 0fac5h, 0faaeh, 0fa97h, 0fa80h, 0fa68h, 0fa50h
	dd 0fa38h, 0fa20h, 0fa07h, 0f9efh, 0f9d6h, 0f9bdh, 0f9a3h, 0f98ah, 0f970h, 0f956h, 0f93ch
	dd 0f922h, 0f908h, 0f8edh, 0f8d2h, 0f8b7h, 0f89ch, 0f881h, 0f865h, 0f84ah, 0f82eh, 0f811h
	dd 0f7f5h, 0f7d9h, 0f7bch, 0f79fh, 0f782h, 0f764h, 0f747h, 0f729h, 0f70bh, 0f6edh, 0f6cfh
	dd 0f6b0h, 0f692h, 0f673h, 0f654h, 0f635h, 0f615h, 0f5f6h, 0f5d6h, 0f5b6h, 0f596h, 0f575h
	dd 0f555h, 0f534h, 0f513h, 0f4f2h, 0f4d0h, 0f4afh, 0f48dh, 0f46bh, 0f449h, 0f427h, 0f404h
	dd 0f3e2h, 0f3bfh, 0f39ch, 0f378h, 0f355h, 0f331h, 0f30eh, 0f2eah, 0f2c5h, 0f2a1h, 0f27ch
	dd 0f258h, 0f233h, 0f20eh, 0f1e8h, 0f1c3h, 0f19dh, 0f177h, 0f151h, 0f12bh, 0f104h, 0f0deh
	dd 0f0b7h, 0f090h, 0f068h, 0f041h, 0f019h, 0eff2h, 0efcah, 0efa2h, 0ef79h, 0ef51h, 0ef28h
	dd 0eeffh, 0eed6h, 0eeadh, 0ee83h, 0ee5ah, 0ee30h, 0ee06h, 0eddch, 0edb1h, 0ed87h, 0ed5ch
	dd 0ed31h, 0ed06h, 0ecdbh, 0ecafh, 0ec83h, 0ec58h, 0ec2bh, 0ebffh, 0ebd3h, 0eba6h, 0eb79h
	dd 0eb4ch, 0eb1fh, 0eaf2h, 0eac4h, 0ea97h, 0ea69h, 0ea3bh, 0ea0dh, 0e9deh, 0e9b0h, 0e981h
	dd 0e952h, 0e923h, 0e8f3h, 0e8c4h, 0e894h, 0e864h, 0e834h, 0e804h, 0e7d3h, 0e7a3h, 0e772h
	dd 0e741h, 0e710h, 0e6deh, 0e6adh, 0e67bh, 0e649h, 0e617h, 0e5e5h, 0e5b3h, 0e580h, 0e54dh
	dd 0e51ah, 0e4e7h, 0e4b4h, 0e481h, 0e44dh, 0e419h, 0e3e5h, 0e3b1h, 0e37ch, 0e348h, 0e313h
	dd 0e2deh, 0e2a9h, 0e274h, 0e23eh, 0e209h, 0e1d3h, 0e19dh, 0e167h, 0e131h, 0e0fah, 0e0c3h
	dd 0e08dh, 0e056h, 0e01eh, 0dfe7h, 0dfb0h, 0df78h, 0df40h, 0df08h, 0ded0h, 0de97h, 0de5fh
	dd 0de26h, 0ddedh, 0ddb4h, 0dd7bh, 0dd41h, 0dd07h, 0dcceh, 0dc94h, 0dc5ah, 0dc1fh, 0dbe5h
	dd 0dbaah, 0db6fh, 0db34h, 0daf9h, 0dabeh, 0da82h, 0da47h, 0da0bh, 0d9cfh, 0d993h, 0d956h
	dd 0d91ah, 0d8ddh, 0d8a0h, 0d863h, 0d826h, 0d7e9h, 0d7abh, 0d76dh, 0d72fh, 0d6f1h, 0d6b3h
	dd 0d675h, 0d636h, 0d5f7h, 0d5b9h, 0d57ah, 0d53ah, 0d4fbh, 0d4bbh, 0d47ch, 0d43ch, 0d3fch
	dd 0d3bch, 0d37bh, 0d33bh, 0d2fah, 0d2b9h, 0d278h, 0d237h, 0d1f5h, 0d1b4h, 0d172h, 0d130h
	dd 0d0eeh, 0d0ach, 0d06ah, 0d027h, 0cfe5h, 0cfa2h, 0cf5fh, 0cf1ch, 0ced8h, 0ce95h, 0ce51h
	dd 0ce0eh, 0cdcah, 0cd85h, 0cd41h, 0ccfdh, 0ccb8h, 0cc73h, 0cc2eh, 0cbe9h, 0cba4h, 0cb5fh
	dd 0cb19h, 0cad3h, 0ca8eh, 0ca48h, 0ca01h, 0c9bbh, 0c975h, 0c92eh, 0c8e7h, 0c8a0h, 0c859h
	dd 0c812h, 0c7cah, 0c783h, 0c73bh, 0c6f3h, 0c6abh, 0c663h, 0c61ah, 0c5d2h, 0c589h, 0c540h
	dd 0c4f7h, 0c4aeh, 0c465h, 0c41bh, 0c3d2h, 0c388h, 0c33eh, 0c2f4h, 0c2aah, 0c260h, 0c215h
	dd 0c1cah, 0c180h, 0c135h, 0c0eah, 0c09eh, 0c053h, 0c007h, 0bfbch, 0bf70h, 0bf24h, 0bed8h
	dd 0be8bh, 0be3fh, 0bdf2h, 0bda5h, 0bd58h, 0bd0bh, 0bcbeh, 0bc71h, 0bc23h, 0bbd6h, 0bb88h
	dd 0bb3ah, 0baech, 0ba9eh, 0ba4fh, 0ba01h, 0b9b2h, 0b963h, 0b914h, 0b8c5h, 0b876h, 0b827h
	dd 0b7d7h, 0b787h, 0b738h, 0b6e8h, 0b698h, 0b647h, 0b5f7h, 0b5a6h, 0b556h, 0b505h, 0b4b4h
	dd 0b463h, 0b412h, 0b3c0h, 0b36fh, 0b31dh, 0b2cbh, 0b279h, 0b227h, 0b1d5h, 0b183h, 0b130h
	dd 0b0deh, 0b08bh, 0b038h, 0afe5h, 0af92h, 0af3eh, 0aeebh, 0ae97h, 0ae44h, 0adf0h, 0ad9ch
	dd 0ad48h, 0acf3h, 0ac9fh, 0ac4bh, 0abf6h, 0aba1h, 0ab4ch, 0aaf7h, 0aaa2h, 0aa4dh, 0a9f7h
	dd 0a9a1h, 0a94ch, 0a8f6h, 0a8a0h, 0a84ah, 0a7f3h, 0a79dh, 0a747h, 0a6f0h, 0a699h, 0a642h
	dd 0a5ebh, 0a594h, 0a53dh, 0a4e5h, 0a48eh, 0a436h, 0a3deh, 0a386h, 0a32eh, 0a2d6h, 0a27eh
	dd 0a225h, 0a1cdh, 0a174h, 0a11bh, 0a0c2h, 0a069h, 0a010h, 9fb7h, 9f5dh, 9f04h, 9eaah
	dd 9e50h, 9df6h, 9d9ch, 9d42h, 9ce7h, 9c8dh, 9c32h, 9bd8h, 9b7dh, 9b22h, 9ac7h, 9a6ch
	dd 9a11h, 99b5h, 995ah, 98feh, 98a2h, 9846h, 97eah, 978eh, 9732h, 96d6h, 9679h, 961ch
	dd 95c0h, 9563h, 9506h, 94a9h, 944ch, 93eeh, 9391h, 9334h, 92d6h, 9278h, 921ah, 91bch
	dd 915eh, 9100h, 90a2h, 9043h, 8fe5h, 8f86h, 8f27h, 8ec8h, 8e69h, 8e0ah, 8dabh, 8d4ch
	dd 8cech, 8c8dh, 8c2dh, 8bcdh, 8b6dh, 8b0dh, 8aadh, 8a4dh, 89edh, 898ch, 892ch, 88cbh
	dd 886bh, 880ah, 87a9h, 8748h, 86e7h, 8685h, 8624h, 85c2h, 8561h, 84ffh, 849dh, 843ch
	dd 83dah, 8377h, 8315h, 82b3h, 8251h, 81eeh, 818bh, 8129h, 80c6h, 8063h, 8000h, 7f9dh
	dd 7f3ah, 7ed6h, 7e73h, 7e0fh, 7dach, 7d48h, 7ce4h, 7c80h, 7c1ch, 7bb8h, 7b54h, 7af0h
	dd 7a8ch, 7a27h, 79c3h, 795eh, 78f9h, 7894h, 782fh, 77cah, 7765h, 7700h, 769bh, 7635h
	dd 75d0h, 756ah, 7504h, 749fh, 7439h, 73d3h, 736dh, 7307h, 72a0h, 723ah, 71d4h, 716dh
	dd 7107h, 70a0h, 7039h, 6fd2h, 6f6bh, 6f04h, 6e9dh, 6e36h, 6dcfh, 6d67h, 6d00h, 6c98h
	dd 6c31h, 6bc9h, 6b61h, 6af9h, 6a91h, 6a29h, 69c1h, 6959h, 68f1h, 6888h, 6820h, 67b7h
	dd 674fh, 66e6h, 667dh, 6614h, 65abh, 6542h, 64d9h, 6470h, 6407h, 639eh, 6334h, 62cbh
	dd 6261h, 61f8h, 618eh, 6124h, 60bah, 6050h, 5fe6h, 5f7ch, 5f12h, 5ea8h, 5e3dh, 5dd3h
	dd 5d69h, 5cfeh, 5c93h, 5c29h, 5bbeh, 5b53h, 5ae8h, 5a7dh, 5a12h, 59a7h, 593ch, 58d1h
	dd 5865h, 57fah, 578fh, 5723h, 56b8h, 564ch, 55e0h, 5574h, 5509h, 549dh, 5431h, 53c5h
	dd 5358h, 52ech, 5280h, 5214h, 51a7h, 513bh, 50ceh, 5062h, 4ff5h, 4f88h, 4f1ch, 4eafh
	dd 4e42h, 4dd5h, 4d68h, 4cfbh, 4c8eh, 4c21h, 4bb4h, 4b46h, 4ad9h, 4a6bh, 49feh, 4990h
	dd 4923h, 48b5h, 4848h, 47dah, 476ch, 46feh, 4690h, 4622h, 45b4h, 4546h, 44d8h, 446ah
	dd 43fbh, 438dh, 431fh, 42b0h, 4242h, 41d3h, 4165h, 40f6h, 4088h, 4019h, 3faah, 3f3bh
	dd 3ecch, 3e5eh, 3defh, 3d80h, 3d11h, 3ca1h, 3c32h, 3bc3h, 3b54h, 3ae5h, 3a75h, 3a06h
	dd 3996h, 3927h, 38b7h, 3848h, 37d8h, 3769h, 36f9h, 3689h, 3619h, 35aah, 353ah, 34cah
	dd 345ah, 33eah, 337ah, 330ah, 329ah, 322ah, 31b9h, 3149h, 30d9h, 3069h, 2ff8h, 2f88h
	dd 2f17h, 2ea7h, 2e37h, 2dc6h, 2d55h, 2ce5h, 2c74h, 2c04h, 2b93h, 2b22h, 2ab1h, 2a41h
	dd 29d0h, 295fh, 28eeh, 287dh, 280ch, 279bh, 272ah, 26b9h, 2648h, 25d7h, 2566h, 24f5h
	dd 2483h, 2412h, 23a1h, 2330h, 22beh, 224dh, 21dch, 216ah, 20f9h, 2087h, 2016h, 1fa4h
	dd 1f33h, 1ec1h, 1e50h, 1ddeh, 1d6dh, 1cfbh, 1c89h, 1c18h, 1ba6h, 1b34h, 1ac2h, 1a51h
	dd 19dfh, 196dh, 18fbh, 1889h, 1817h, 17a6h, 1734h, 16c2h, 1650h, 15deh, 156ch, 14fah
	dd 1488h, 1416h, 13a4h, 1332h, 12c0h, 124eh, 11dch, 1169h, 10f7h, 1085h, 1013h, 0fa1h
	dd 0f2fh, 0ebdh, 0e4ah, 0dd8h, 0d66h, 0cf4h, 0c81h, 0c0fh, 0b9dh, 0b2bh, 0ab8h, 0a46h
	dd 9d4h, 961h, 8efh, 87dh, 80bh, 798h, 726h, 6b4h, 641h, 5cfh, 55ch, 4eah, 478h, 405h
	dd 393h, 321h, 2aeh, 23ch, 1cah, 157h, 0e5h, 72h, 0
CosTable16_t ends
CosTable16 CosTable16_t <>

; VFXA's VFX_Cos_Sin, unchanged.
VFX_Cos_Sin16 proc uses ebx esi edi, p_angle:dword, p_cos:dword, p_sin:dword
	push es
	mov ebx, dword ptr p_angle
	and ebx, ebx
	jns jmp_10058b11
jmp_10058b01:
	add ebx, 0e10h
	js jmp_10058b01
	jmp jmp_10058b11
jmp_10058b0b:
	sub ebx, 0e10h
jmp_10058b11:
	cmp ebx, 0e10h
	jg jmp_10058b0b
	cmp ebx, 708h
	ja jmp_10058b59
	cmp ebx, 384h
	ja jmp_10058b3c
	shl ebx, 2
	mov eax, dword ptr [CosTable16+ebx]
	neg ebx
	mov edx, dword ptr [CosTable16+0e10h+ebx]
	jmp jmp_10058b9b
jmp_10058b3c:
	neg ebx
	add ebx, 708h
	shl ebx, 2
	mov eax, dword ptr [CosTable16+ebx]
	neg eax
	neg ebx
	mov edx, dword ptr [CosTable16+0e10h+ebx]
	jmp jmp_10058b9b
jmp_10058b59:
	neg ebx
	add ebx, 0e10h
	cmp ebx, 384h
	ja jmp_10058b7e
	shl ebx, 2
	mov eax, dword ptr [CosTable16+ebx]
	neg ebx
	mov edx, dword ptr [CosTable16+0e10h+ebx]
	neg edx
	jmp jmp_10058b9b
jmp_10058b7e:
	neg ebx
	add ebx, 708h
	shl ebx, 2
	mov eax, dword ptr [CosTable16+ebx]
	neg eax
	neg ebx
	mov edx, dword ptr [CosTable16+0e10h+ebx]
	neg edx
jmp_10058b9b:
	mov ebx, dword ptr p_cos
	mov dword ptr [ebx], eax
	mov ebx, dword ptr p_sin
	mov dword ptr [ebx], edx
	pop es
	ret
VFX_Cos_Sin16 endp

; VFXA's VFX_fixed_mul, unchanged.
VFX_fixed_mul16 proc uses ebx esi edi, p_m1:dword, p_m2:dword, p_result:dword
	push es
	mov eax, dword ptr p_m1
	imul dword ptr p_m2
	add eax, 8000h
	adc edx, 0
	mov ax, dx
	ror eax, 10h
	mov edi, dword ptr p_result
	mov dword ptr [edi], eax
	pop es
	ret
VFX_fixed_mul16 endp

; VFXA's VFX_point_transform, unchanged.
VFX_point_transform16 proc uses ebx esi edi, p_in:dword, p_out:dword, p_origin:dword, p_rot:dword, p_xScale:dword, p_yScale:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword
	push es
	cld
	push ds
	pop es
	lea eax, l_unk0x08
	push eax
	lea eax, l_unk0x04
	push eax
	push dword ptr p_rot
	call VFX_Cos_Sin16
	add esp, 0ch
	mov esi, dword ptr p_in
	mov edi, dword ptr p_origin
	mov eax, dword ptr [esi]
	sub eax, dword ptr [edi]
	shl eax, 10h
	imul dword ptr p_xScale
	add eax, 8000h
	adc edx, 0
	mov ebx, edx
	mov eax, ebx
	imul dword ptr l_unk0x04
	add eax, 8000h
	adc edx, 0
	mov ax, dx
	ror eax, 10h
	mov dword ptr l_unk0x0c, eax
	mov eax, ebx
	imul dword ptr l_unk0x08
	add eax, 8000h
	adc edx, 0
	mov ax, dx
	ror eax, 10h
	mov dword ptr l_unk0x14, eax
	mov eax, dword ptr [esi+4]
	sub eax, dword ptr [edi+4]
	shl eax, 10h
	imul dword ptr p_yScale
	add eax, 8000h
	adc edx, 0
	mov ecx, edx
	mov eax, ecx
	imul dword ptr l_unk0x04
	add eax, 8000h
	adc edx, 0
	mov ax, dx
	ror eax, 10h
	mov dword ptr l_unk0x18, eax
	mov eax, ecx
	imul dword ptr l_unk0x08
	add eax, 8000h
	adc edx, 0
	mov ax, dx
	ror eax, 10h
	mov dword ptr l_unk0x10, eax
	mov esi, dword ptr p_out
	mov edx, dword ptr l_unk0x0c
	sub edx, dword ptr l_unk0x10
	add edx, dword ptr [edi]
	mov dword ptr [esi], edx
	mov edx, dword ptr l_unk0x18
	add edx, dword ptr l_unk0x14
	add edx, dword ptr [edi+4]
	mov dword ptr [esi+4], edx
	pop es
	ret
VFX_point_transform16 endp

; VFXA's VFX_font_height, unchanged.
VFX_font_height16 proc uses ebx esi edi, p_font:dword
	push es
	mov esi, dword ptr p_font
	mov eax, dword ptr [esi+8]
	pop es
	ret
VFX_font_height16 endp

; VFXA's VFX_character_width, unchanged.
VFX_character_width16 proc uses ebx esi edi, p_font:dword, p_character:dword
	push es
	mov eax, dword ptr p_character
	shl eax, 2
	add eax, dword ptr p_font
	add eax, 10h
	mov esi, dword ptr [eax]
	add esi, dword ptr p_font
	mov eax, dword ptr [esi]
	pop es
	ret
VFX_character_width16 endp

; VFXA's VFX_character_draw, for 16-bit pixels: p_colorTranslate is a table of 16-bit pixels, where
; 0x8000 is transparent, and is required (VFXA's untranslated copy is gone).
VFX_character_draw16 proc uses ebx esi edi, p_pane:dword, p_x:dword, p_y:dword, p_font:dword, p_character:dword, p_colorTranslate:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword, l_unk0x28:dword, l_unk0x2c:dword, l_unk0x30:dword
	local l_unk0x34:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_pane
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x28, eax
	jle jmp_10058d4f
	shl eax, 1
	mov dword ptr l_unk0x2c, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_10058d4f
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x30, eax
	cmp eax, 0
	jg jmp_10058d03
	mov eax, 0
jmp_10058d03:
	mov dword ptr l_unk0x14, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x34, eax
	cmp eax, 0
	jg jmp_10058d16
	mov eax, 0
jmp_10058d16:
	mov dword ptr l_unk0x18, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x28
	dec edx
	cmp eax, edx
	jl jmp_10058d26
	mov eax, edx
jmp_10058d26:
	mov dword ptr l_unk0x1c, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_10058d35
	mov eax, edx
jmp_10058d35:
	mov dword ptr l_unk0x20, eax
	mov eax, dword ptr l_unk0x1c
	cmp eax, dword ptr l_unk0x14
	jl jmp_10058d5a
	mov eax, dword ptr l_unk0x20
	cmp eax, dword ptr l_unk0x18
	jl jmp_10058d5a
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x24, eax
	jmp jmp_10058d65
jmp_10058d4f:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_10058d5a:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_10058d65:
	mov eax, dword ptr l_unk0x30
	add dword ptr p_x, eax
	mov eax, dword ptr l_unk0x34
	add dword ptr p_y, eax
	mov esi, dword ptr p_font
	mov edx, dword ptr [esi+8]
	mov eax, dword ptr p_character
	shl eax, 2
	add eax, dword ptr p_font
	add eax, 10h
	mov esi, dword ptr [eax]
	add esi, dword ptr p_font
	mov dword ptr l_unk0x08, 0
	mov ecx, dword ptr [esi]
	mov dword ptr l_unk0x04, ecx
	cmp ecx, 0
	je jmp_10058e39
	add esi, 4
	mov edi, dword ptr p_pane
	mov eax, dword ptr l_unk0x1c
	inc eax
	sub eax, ecx
	sub eax, dword ptr p_x
	jns jmp_10058db6
	add ecx, eax
	jle jmp_10058e39
jmp_10058db6:
	mov eax, dword ptr p_x
	sub eax, dword ptr l_unk0x14
	jns jmp_10058dc7
	add ecx, eax
	jle jmp_10058e39
	sub esi, eax
	sub dword ptr p_x, eax
jmp_10058dc7:
	mov eax, dword ptr l_unk0x20
	inc eax
	sub eax, edx
	sub eax, dword ptr p_y
	jns jmp_10058dd6
	add edx, eax
	jle jmp_10058e39
jmp_10058dd6:
	mov eax, dword ptr p_y
	sub eax, dword ptr l_unk0x18
	jns jmp_10058deb
	add edx, eax
	jle jmp_10058e39
	sub dword ptr p_y, eax
	imul eax, dword ptr l_unk0x04
	sub esi, eax
jmp_10058deb:
	mov dword ptr l_unk0x10, edx
	mov eax, dword ptr p_y
	imul dword ptr l_unk0x28
	add eax, dword ptr p_x
	add eax, dword ptr p_x
	add eax, dword ptr l_unk0x24
	mov edi, eax
	mov dword ptr l_unk0x08, ecx
	sub dword ptr l_unk0x04, ecx
	mov eax, dword ptr l_unk0x28
	sub eax, ecx
	sub eax, ecx
	mov dword ptr l_unk0x0c, eax
	mov edx, dword ptr l_unk0x10
	jecxz jmp_10058e39
	mov ebx, dword ptr p_colorTranslate
jmp_10058e17:
	movzx eax, byte ptr [esi]
	mov ax, word ptr [ebx+eax*2]
	cmp ax, 8000h
	je jmp_10058e27
	mov word ptr [edi], ax
jmp_10058e27:
	inc esi
	add edi, 2
	loop jmp_10058e17
	mov ecx, dword ptr l_unk0x08
	add esi, dword ptr l_unk0x04
	add edi, dword ptr l_unk0x0c
	dec edx
	jne jmp_10058e17
jmp_10058e39:
	mov eax, dword ptr l_unk0x04
	add eax, dword ptr l_unk0x08
	pop es
	ret
VFX_character_draw16 endp

; VFXA's VFX_string_draw, unchanged but for drawing through VFX_character_draw16.
VFX_string_draw16 proc uses ebx esi edi, p_pane:dword, p_x:dword, p_y:dword, p_font:dword, p_string:dword, p_colorTranslate:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_string
	mov edi, dword ptr p_x
jmp_10058e55:
	movzx eax, byte ptr [esi]
	push dword ptr p_colorTranslate
	push eax
	push dword ptr p_font
	push dword ptr p_y
	push edi
	push dword ptr p_pane
	call VFX_character_draw16
	add esp, 18h
	add edi, eax
	inc esi
	cmp byte ptr [esi], 0
	jne jmp_10058e55
	pop es
	ret
VFX_string_draw16 endp

; VFXA's VFX_line_to_pane, for 16-bit pixels.
VFX_line_to_pane16 proc uses ebx esi edi, p_target:dword, p_y:dword, p_lineBuffer:dword, p_lineLength:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword, l_unk0x14:dword, l_unk0x18:dword
	local l_unk0x1c:dword, l_unk0x20:dword, l_unk0x24:dword, l_unk0x28:dword
	push es
	cld
	push ds
	pop es
	mov esi, dword ptr p_target
	mov ebx, dword ptr [esi]
	mov eax, dword ptr [ebx+4]
	inc eax
	mov dword ptr l_unk0x1c, eax
	jle jmp_10058f00
	shl eax, 1
	mov dword ptr l_unk0x20, eax
	mov eax, dword ptr [ebx+8]
	inc eax
	mov ecx, eax
	jle jmp_10058f00
	mov eax, dword ptr [esi+4]
	mov dword ptr l_unk0x24, eax
	cmp eax, 0
	jg jmp_10058eb4
	mov eax, 0
jmp_10058eb4:
	mov dword ptr l_unk0x08, eax
	mov eax, dword ptr [esi+8]
	mov dword ptr l_unk0x28, eax
	cmp eax, 0
	jg jmp_10058ec7
	mov eax, 0
jmp_10058ec7:
	mov dword ptr l_unk0x0c, eax
	mov eax, dword ptr [esi+0ch]
	mov edx, dword ptr l_unk0x1c
	dec edx
	cmp eax, edx
	jl jmp_10058ed7
	mov eax, edx
jmp_10058ed7:
	mov dword ptr l_unk0x10, eax
	mov eax, dword ptr [esi+10h]
	mov edx, ecx
	dec edx
	cmp eax, edx
	jl jmp_10058ee6
	mov eax, edx
jmp_10058ee6:
	mov dword ptr l_unk0x14, eax
	mov eax, dword ptr l_unk0x10
	cmp eax, dword ptr l_unk0x08
	jl jmp_10058f0b
	mov eax, dword ptr l_unk0x14
	cmp eax, dword ptr l_unk0x0c
	jl jmp_10058f0b
	mov eax, dword ptr [ebx]
	mov dword ptr l_unk0x18, eax
	jmp jmp_10058f16
jmp_10058f00:
	mov eax, 0ffffffffh
	pop es
	ret
jmp_10058f0b:
	mov eax, 0fffffffeh
	pop es
	ret
jmp_10058f16:
	mov dword ptr l_unk0x04, 0
	mov eax, dword ptr l_unk0x24
	add dword ptr l_unk0x04, eax
	mov eax, dword ptr l_unk0x28
	add dword ptr p_y, eax
	mov esi, dword ptr p_lineBuffer
	mov edi, dword ptr p_target
	mov ecx, dword ptr p_lineLength
	mov eax, dword ptr l_unk0x10
	sub eax, dword ptr l_unk0x04
	inc eax
	sub eax, ecx
	jns jmp_10058f41
	add ecx, eax
	jle jmp_10058f81
jmp_10058f41:
	mov eax, dword ptr l_unk0x04
	sub eax, dword ptr l_unk0x08
	jns jmp_10058f52
	add ecx, eax
	jle jmp_10058f81
	sub esi, eax
	sub dword ptr l_unk0x04, eax
jmp_10058f52:
	mov eax, dword ptr l_unk0x14
	sub eax, dword ptr p_y
	js jmp_10058f81
	mov eax, dword ptr p_y
	sub eax, dword ptr l_unk0x0c
	js jmp_10058f81
	mov eax, dword ptr p_y
	imul dword ptr l_unk0x1c
	add eax, dword ptr l_unk0x04
	add eax, dword ptr l_unk0x04
	add eax, dword ptr l_unk0x18
	mov edi, eax
	mov edx, ecx
	and ecx, 3
	rep movsb
	mov ecx, edx
	shr ecx, 2
	rep movsd
jmp_10058f81:
	pop es
	ret
VFX_line_to_pane16 endp

; VFXA's VFX_window_fade, unchanged (it fades the 8-bit palette).
VFX_window_fade16 proc uses ebx esi edi, p_buffer:dword, p_palette:dword, p_intervals:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword, l_unk0x10:dword
	push es
	cld
	push ds
	pop es
	mov edi, offset color_sb16
	mov eax, 0
	mov ecx, 40h
	rep stosd
	mov esi, dword ptr p_buffer
	mov eax, dword ptr [esi+4]
	inc eax
	mov ecx, dword ptr [esi+8]
	inc ecx
	imul ecx, eax
	mov esi, dword ptr [esi]
	mov edi, offset color_list16
	mov dword ptr l_unk0x04, 0ffffffffh
jmp_10058fc1:
	mov eax, 0
	lodsb
	cmp byte ptr [color_sb16+eax], 0
	jne jmp_10058ff4
	or byte ptr [color_sb16+eax], 1
	stosb
	inc dword ptr l_unk0x04
	mov ebx, eax
	shl ebx, 1
	add ebx, eax
	add ebx, offset color_buffer16
	push ecx
	push ebx
	push eax
	call dword ptr [VFX_DAC_read16]
	add esp, 8
	pop ecx
jmp_10058ff4:
	dec ecx
	jne jmp_10058fc1
	mov dword ptr l_unk0x08, 0
	mov ecx, dword ptr l_unk0x04
	mov ebx, 0
	mov esi, dword ptr p_palette
jmp_10059009:
	movzx eax, byte ptr [color_list16+ecx]
	mov ebx, eax
	shl ebx, 1
	add ebx, eax
	mov edx, 2
jmp_1005901b:
	mov ah, 0ffh
	mov al, byte ptr [color_buffer16+ebx]
	sub al, byte ptr [esi+ebx]
	jge jmp_1005902c
	mov ah, 1
	neg al
jmp_1005902c:
	mov byte ptr [color_sb16+ebx], ah
	mov byte ptr [color_delta16+ebx], al
	cmp al, byte ptr l_unk0x08
	jle jmp_10059040
	mov byte ptr l_unk0x08, al
jmp_10059040:
	inc ebx
	dec edx
	jns jmp_1005901b
	dec ecx
	jns jmp_10059009
	mov ecx, dword ptr l_unk0x04
	mov edi, offset color_error16
	mov al, byte ptr l_unk0x08
	shr al, 1
	mov ah, al
	shr ecx, 1
	rep stosw
	adc ecx, 0
	rep stosb
	movzx esi, byte ptr l_unk0x08
	cmp esi, 0
	je jmp_10059105
	mov eax, dword ptr p_intervals
	mov edx, 0
	shld edx, eax, 10h
	shl eax, 10h
	div esi
	mov dword ptr l_unk0x0c, eax
	mov dword ptr l_unk0x10, 8000h
jmp_10059088:
	mov ecx, dword ptr l_unk0x04
jmp_1005908b:
	movzx eax, byte ptr [color_list16+ecx]
	mov ebx, eax
	shl ebx, 1
	add ebx, eax
	mov edx, 2
jmp_1005909d:
	mov al, byte ptr [color_error16+ebx+edx]
	add al, byte ptr [color_delta16+ebx+edx]
	cmp al, byte ptr l_unk0x08
	jl jmp_100590c1
	sub al, byte ptr l_unk0x08
	mov ah, byte ptr [color_sb16+ebx+edx]
	add byte ptr [color_buffer16+ebx+edx], ah
jmp_100590c1:
	mov byte ptr [color_error16+ebx+edx], al
	dec edx
	jns jmp_1005909d
	push ecx
	mov eax, ebx
	add eax, offset color_buffer16
	push eax
	movzx eax, byte ptr [color_list16+ecx]
	push eax
	call dword ptr [VFX_DAC_write16]
	add esp, 8
	pop ecx
	dec ecx
	jns jmp_1005908b
	mov eax, dword ptr l_unk0x0c
	add dword ptr l_unk0x10, eax
	cmp word ptr l_unk0x10+2, 1
	jl jmp_10059102
jmp_100590f6:
	call dword ptr [VFX_wait_vblank_leading16]
	dec word ptr l_unk0x10+2
	jne jmp_100590f6
jmp_10059102:
	dec esi
	jne jmp_10059088
jmp_10059105:
	pop es
	ret
VFX_window_fade16 endp

; VFXA's VFX_color_scan, unchanged: it scans 8-bit pixels.
VFX_color_scan16 proc uses ebx esi edi, p_pane:dword, p_colors:dword
	local l_unk0x04:dword, l_unk0x08:dword, l_unk0x0c:dword
	push es
	cld
	push ds
	pop es
	mov edi, offset color_sb16
	mov eax, 0
	mov ecx, 40h
	rep stosd
	mov esi, dword ptr p_pane
	mov ecx, dword ptr [esi+0ch]
	sub ecx, dword ptr [esi+4]
	mov dword ptr l_unk0x08, ecx
	mov ebx, dword ptr [esi+10h]
	sub ebx, dword ptr [esi+8]
	mov esi, dword ptr [esi]
	mov eax, dword ptr [esi+4]
	inc eax
	mov dword ptr l_unk0x0c, eax
	mov esi, dword ptr p_pane
	mov eax, dword ptr [esi+8]
	imul dword ptr l_unk0x0c
	add eax, dword ptr [esi+4]
	mov esi, dword ptr [esi]
	mov esi, dword ptr [esi]
	add esi, eax
	mov edi, dword ptr p_colors
	mov dword ptr l_unk0x04, 0ffffffffh
jmp_10059160:
	mov eax, 0
	movzx eax, byte ptr [esi+ecx]
	cmp byte ptr [color_sb16+eax], 0
	jne jmp_10059182
	or byte ptr [color_sb16+eax], 1
	inc dword ptr l_unk0x04
	cmp edi, 0
	je jmp_10059182
	stosd
jmp_10059182:
	dec ecx
	jns jmp_10059160
	mov ecx, dword ptr l_unk0x08
	add esi, dword ptr l_unk0x0c
	dec ebx
	jns jmp_10059160
	mov eax, dword ptr l_unk0x04
	inc eax
	pop es
	ret
VFX_color_scan16 endp

	end
