#!/usr/bin/env python3
"""Write reccmp/<target>-vfx.csv: the names of the Miles Design VFX objects' data (3rdparty/vfx).

The VFX sources keep their data under static labels, several of them at one address and some
with the same name in two objects (line_size, lookaside), so they can't be annotated by name.
The objects assemble identical to the game's, so each label's original address is its object's
original data address plus its offset. For every address in the three objects' data, this
writes the name reccmp takes from the rebuild's PDB (of several labels at one address, the one
with the largest type), so the original side of a compare reads the same names. Data the
headers (common/include) annotate by name is left out.

Run from the build directory, with reccmp's environment (as reccmp-reccmp), after a build:

    python ../tools/vfx_names.py --target MW2SHELL
"""

import argparse
import logging
import os
import re
import sys

from reccmp.compare import Compare
from reccmp.project.detect import argparse_add_project_target_args, argparse_parse_project_target
from reccmp.types import ImageId

# Each object's first data label, its data's original address and its data's size.
OBJECTS = {
    "MW2SHELL": [
        ("VFX_describe_driver", 0x100687CC, 0x19F0),  # VFXA
        ("VP_R", 0x100666A0, 0x1D0),  # VFX3D
        ("dfactor_1", 0x10064CD8, 0x1920),  # VFXREND
    ],
    "MW2": [
        ("VFX_describe_driver", 0x100AB100, 0x19F0),
        ("VP_R", 0x100A5560, 0x1D0),
        ("dfactor_1", 0x100A3958, 0x1920),
    ],
    "MW2MATROX": [
        ("VFX_describe_driver", 0x100A8758, 0x19F0),
        ("VP_R", 0x100A4664, 0x1D0),
        ("dfactor_1", 0x100A6394, 0x1920),
    ],
}

HEADERS = ["vfxa.h", "vfx3d.h", "vfxrend.h"]


def annotated_names(root, target):
    names = set()
    for header in HEADERS:
        with open(os.path.join(root, "common", "include", header), encoding="utf-8") as file:
            text = file.read()
        names.update(re.findall(r"^// GLOBAL: " + target + r" 0x[0-9a-f]+\n(?:// GLOBAL: \w+ 0x[0-9a-f]+\n)*// (\w+)$", text, re.M))
    return names


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    argparse_add_project_target_args(parser)
    args = parser.parse_args()
    logging.basicConfig(level=logging.WARNING)

    target = argparse_parse_project_target(args=args)
    root = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
    skip = annotated_names(root, target.target_id)
    compare = Compare.from_target(target)
    # pylint: disable=protected-access
    db = compare._db

    rows = []
    for first, orig, size in OBJECTS[target.target_id]:
        starts = [e for e in db.all(ImageId.RECOMP) if e.name == first]
        if len(starts) != 1:
            sys.exit(f"{first}: expected one recompiled symbol, found {len(starts)}")
        base = starts[0].recomp_addr
        for entity in db.all_in_range(ImageId.RECOMP, range(base, base + size)):
            if entity.name and entity.name not in skip:
                rows.append((orig + entity.recomp_addr - base, entity.name))

    path = os.path.join(root, "reccmp", f"{target.target_id.lower()}-vfx.csv")
    with open(path, "w", encoding="utf-8", newline="\n") as file:
        file.write("# Generated by tools/vfx_names.py: the data labels of the Miles Design VFX objects (3rdparty/vfx:\n")
        file.write("# VFXA, VFX3D, VFXREND) that their headers don't annotate, at their original addresses, under\n")
        file.write("# the name reccmp takes for each from the rebuild (several labels can share an address).\n")
        file.write("address,type,name\n")
        for addr, name in sorted(rows):
            file.write(f"{addr:#010x},global,{name}\n")
    print(f"{path}: {len(rows)} names")


if __name__ == "__main__":
    main()
