# The target whose original was built with VC++ 4.0: MW2_MATROX.DLL, the simulator of the
# Matrox Mystique edition.
#
# Included by vc40/CMakeLists.txt, the VC++ 4.0 sub-project, and by the top-level project
# when it has no VC++ 4.0 to hand it to (a VC++ 4.1 build without DEMECH2_MSVC40_ROOT).
# Expects DEMECH2_SOURCE_DIR, asm_or_c and ${vfxa} (cmake/masm.cmake), demech2_add_dll
# (cmake/game_dll.cmake) and the ddraw, dplay and wail32 import library targets.

# MW2_MATROX.DLL (linked 1996-08-22 by LINK 3.00): the same C as MW2.DLL at /Od /Oi /G5, with
# the release CRT (4.0's LIBCMT, which its CRT matches far better than 4.1's), drawing through
# Matrox's MSI95.DLL instead of DirectDraw. Most of its functions are 1.1's, byte for byte or
# with their stack slots permuted, and carry MW2MATROX annotations next to MW2's
# (tools/port_annotations.py). MW2_MATROX is defined for the edition's own code.
#
# The sources are MW2's, in the edition's link order: its objects hold MW2's units in another
# order, found from the functions they share (config.c's first ten functions sit in an object
# of their own, after staticmem.c, which a shared unit can't reproduce). The edition's own
# objects (the A3D renderer, the units it rewrote) aren't written yet.
function(demech2_add_mw2matrox)
  demech2_add_dll(mw2matrox
    ID MW2MATROX
    SOURCE_DIR MW2
    OUTPUT_NAME MW2_MATROX
    RUNTIME MultiThreaded
    SOURCES
      "${DEMECH2_SOURCE_DIR}/MW2/src/missionaudio.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/namehash.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/anim2d.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/transform.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/cdaudio.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/shapelists.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/gamecd.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/network.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/targeting.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/ticks.${asm_or_c}"
      "${DEMECH2_SOURCE_DIR}/MW2/src/gdi.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/eyepoint.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/inifile.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/boundbox.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/sndunpack.${asm_or_c}"
      "${DEMECH2_SOURCE_DIR}/MW2/src/config.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/soundlimits.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/random.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/prjfile.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mechclass.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mechdamage.c"
      ${vfx3d}
      "${DEMECH2_SOURCE_DIR}/MW2/src/quadtree.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/faceshade.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/brightnessmenu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixedmul.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/render.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/targetpanel.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/maneuvers.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/cockpitpanel.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/hud.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mapview.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/clock.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/objective.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/cmdline.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/recordstacks.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/statuspanels.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/collision.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/wtbshapes.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/joystick.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/callbacks.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/gridobject.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/shape.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/shapegeom.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/view.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/bwd.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/debris.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mw2prj.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/weapons.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/palette.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/bwdnames.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/ramp.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/pausebanner.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/debugbreak.c"
      ${vfxrend}
      "${DEMECH2_SOURCE_DIR}/MW2/src/object.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/gamekeys.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/midi.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/settings.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/audio.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fadepal.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/recttransition.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixeddiv.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/world.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/resource.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/supanim.c"
      ${vfxa}
      "${DEMECH2_SOURCE_DIR}/MW2/src/palfade.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mouse.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/animation.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/shapecollision.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/geocache.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/players.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/loadres.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/camerashake.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/error.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/keyboard.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/shots.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/classtable.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/logwindow.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/screenshot.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/objectanim.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/screenscale.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/team.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/resourcename.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/cockpit.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/dorcs.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/timedoverlays.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/perf.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/staticmem.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/startup.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mw2log.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/refreshmode.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/inputmap.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/menucontrols.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/missionsetup.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/ai.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/poolsizes.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/debugprint.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/environment.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/soundfx.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/ray.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/bargauges.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/muldiv.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/netio.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/gifsave.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mechviewpanel.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/speech.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/gpanim.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/brightness.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/overlay.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/lancemenu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/dispdib.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/simmain.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mechreload.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/menu.c"
      # Not placed yet: units with no function found in the edition (data-only units, fixed-point
      # helpers it may have replaced, and the units the renderer replaced, such as directdraw.c),
      # linked after the others until the callers' Matrox versions are written, in MW2's order.
      "${DEMECH2_SOURCE_DIR}/MW2/src/approxlen.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/weapondata.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/integrate.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/inradius.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/emptyfns.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mainmenu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/bandpoly.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/commandpointmenu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/muldiv14.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixedsqrt.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/sqrtguess.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixeddiv29.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixedmul29.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/weaponpanel.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/audiomenu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/depthsort.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/scaledelta.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/crossdiv.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/lerp.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/damagepanel.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixeddot27.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixeddot29.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/shiftdiv.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/bwdkeywords.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/polydraw.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixeddivu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixedmul30.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/aiweapons.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/commandmenu.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mulratio.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mulnorm16.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/muladddiv.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/artillery.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/setres.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mekfile.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/palidentity.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/door.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/fixedtrig.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/lineofsight.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/texpoly.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/horizon.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/mechcollision.c"
      "${DEMECH2_SOURCE_DIR}/MW2/src/directdraw.c"
      "${DEMECH2_SOURCE_DIR}/MW2/MW2.def"
    COMPILE_OPTIONS "$<$<COMPILE_LANGUAGE:C,CXX>:/G5;/DMW2_MATROX>"
    LINK_OPTIONS /DEBUG /INCREMENTAL:no
    LIBRARIES winmm.lib wail32 ddraw dplay kernel32.lib user32.lib gdi32.lib advapi32.lib
  )
  # The edition expands mouse.c's __inline IsInsideWindow into MousePoll, where 1.1 calls it.
  set_source_files_properties("${DEMECH2_SOURCE_DIR}/MW2/src/mouse.c" PROPERTIES COMPILE_OPTIONS /Ob1)
endfunction()
